<?php
/**
 * AccessDomainsCreateDomainsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * AccessDomainsCreateDomainsRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccessDomainsCreateDomainsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccessDomainsCreateDomainsRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'default' => '\ClientApi\PveClient\Model\PveBoolean',
        'comment' => 'string',
        'tfa' => 'string',
        'type' => 'string',
        'server1' => 'string',
        'server2' => 'string',
        'base_dn' => 'string',
        'bind_dn' => 'string',
        'password' => 'string',
        'user_attr' => 'string',
        'port' => 'int',
        'secure' => '\ClientApi\PveClient\Model\PveBoolean',
        'sslversion' => '\ClientApi\PveClient\Model\PveSslversionEnum',
        'verify' => '\ClientApi\PveClient\Model\PveBoolean',
        'capath' => 'string',
        'cert' => 'string',
        'certkey' => 'string',
        'filter' => 'string',
        'sync_attributes' => 'string',
        'user_classes' => 'string',
        'group_dn' => 'string',
        'group_name_attr' => 'string',
        'group_filter' => 'string',
        'group_classes' => 'string',
        'sync_defaults_options' => 'string',
        'mode' => '\ClientApi\PveClient\Model\PveModeEnum',
        'case_sensitive' => '\ClientApi\PveClient\Model\PveBoolean',
        'domain' => 'string',
        'issuer_url' => 'string',
        'client_id' => 'string',
        'client_key' => 'string',
        'autocreate' => '\ClientApi\PveClient\Model\PveBoolean',
        'username_claim' => 'string',
        'groups_claim' => 'string',
        'groups_autocreate' => '\ClientApi\PveClient\Model\PveBoolean',
        'groups_overwrite' => '\ClientApi\PveClient\Model\PveBoolean',
        'prompt' => 'string',
        'scopes' => 'string',
        'acr_values' => 'string',
        'query_userinfo' => '\ClientApi\PveClient\Model\PveBoolean',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'default' => null,
        'comment' => null,
        'tfa' => 'pve-tfa-config',
        'type' => null,
        'server1' => 'address',
        'server2' => 'address',
        'base_dn' => null,
        'bind_dn' => null,
        'password' => null,
        'user_attr' => null,
        'port' => null,
        'secure' => null,
        'sslversion' => null,
        'verify' => null,
        'capath' => null,
        'cert' => null,
        'certkey' => null,
        'filter' => null,
        'sync_attributes' => null,
        'user_classes' => 'ldap-simple-attr-list',
        'group_dn' => null,
        'group_name_attr' => 'ldap-simple-attr',
        'group_filter' => null,
        'group_classes' => 'ldap-simple-attr-list',
        'sync_defaults_options' => 'realm-sync-options',
        'mode' => null,
        'case_sensitive' => null,
        'domain' => null,
        'issuer_url' => null,
        'client_id' => null,
        'client_key' => null,
        'autocreate' => null,
        'username_claim' => null,
        'groups_claim' => null,
        'groups_autocreate' => null,
        'groups_overwrite' => null,
        'prompt' => null,
        'scopes' => null,
        'acr_values' => null,
        'query_userinfo' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'default' => false,
        'comment' => false,
        'tfa' => false,
        'type' => false,
        'server1' => false,
        'server2' => false,
        'base_dn' => false,
        'bind_dn' => false,
        'password' => false,
        'user_attr' => false,
        'port' => false,
        'secure' => false,
        'sslversion' => false,
        'verify' => false,
        'capath' => false,
        'cert' => false,
        'certkey' => false,
        'filter' => false,
        'sync_attributes' => false,
        'user_classes' => false,
        'group_dn' => false,
        'group_name_attr' => false,
        'group_filter' => false,
        'group_classes' => false,
        'sync_defaults_options' => false,
        'mode' => false,
        'case_sensitive' => false,
        'domain' => false,
        'issuer_url' => false,
        'client_id' => false,
        'client_key' => false,
        'autocreate' => false,
        'username_claim' => false,
        'groups_claim' => false,
        'groups_autocreate' => false,
        'groups_overwrite' => false,
        'prompt' => false,
        'scopes' => false,
        'acr_values' => false,
        'query_userinfo' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default' => 'default',
        'comment' => 'comment',
        'tfa' => 'tfa',
        'type' => 'type',
        'server1' => 'server1',
        'server2' => 'server2',
        'base_dn' => 'base_dn',
        'bind_dn' => 'bind_dn',
        'password' => 'password',
        'user_attr' => 'user_attr',
        'port' => 'port',
        'secure' => 'secure',
        'sslversion' => 'sslversion',
        'verify' => 'verify',
        'capath' => 'capath',
        'cert' => 'cert',
        'certkey' => 'certkey',
        'filter' => 'filter',
        'sync_attributes' => 'sync_attributes',
        'user_classes' => 'user_classes',
        'group_dn' => 'group_dn',
        'group_name_attr' => 'group_name_attr',
        'group_filter' => 'group_filter',
        'group_classes' => 'group_classes',
        'sync_defaults_options' => 'sync-defaults-options',
        'mode' => 'mode',
        'case_sensitive' => 'case-sensitive',
        'domain' => 'domain',
        'issuer_url' => 'issuer-url',
        'client_id' => 'client-id',
        'client_key' => 'client-key',
        'autocreate' => 'autocreate',
        'username_claim' => 'username-claim',
        'groups_claim' => 'groups-claim',
        'groups_autocreate' => 'groups-autocreate',
        'groups_overwrite' => 'groups-overwrite',
        'prompt' => 'prompt',
        'scopes' => 'scopes',
        'acr_values' => 'acr-values',
        'query_userinfo' => 'query-userinfo',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default' => 'setDefault',
        'comment' => 'setComment',
        'tfa' => 'setTfa',
        'type' => 'setType',
        'server1' => 'setServer1',
        'server2' => 'setServer2',
        'base_dn' => 'setBaseDn',
        'bind_dn' => 'setBindDn',
        'password' => 'setPassword',
        'user_attr' => 'setUserAttr',
        'port' => 'setPort',
        'secure' => 'setSecure',
        'sslversion' => 'setSslversion',
        'verify' => 'setVerify',
        'capath' => 'setCapath',
        'cert' => 'setCert',
        'certkey' => 'setCertkey',
        'filter' => 'setFilter',
        'sync_attributes' => 'setSyncAttributes',
        'user_classes' => 'setUserClasses',
        'group_dn' => 'setGroupDn',
        'group_name_attr' => 'setGroupNameAttr',
        'group_filter' => 'setGroupFilter',
        'group_classes' => 'setGroupClasses',
        'sync_defaults_options' => 'setSyncDefaultsOptions',
        'mode' => 'setMode',
        'case_sensitive' => 'setCaseSensitive',
        'domain' => 'setDomain',
        'issuer_url' => 'setIssuerUrl',
        'client_id' => 'setClientId',
        'client_key' => 'setClientKey',
        'autocreate' => 'setAutocreate',
        'username_claim' => 'setUsernameClaim',
        'groups_claim' => 'setGroupsClaim',
        'groups_autocreate' => 'setGroupsAutocreate',
        'groups_overwrite' => 'setGroupsOverwrite',
        'prompt' => 'setPrompt',
        'scopes' => 'setScopes',
        'acr_values' => 'setAcrValues',
        'query_userinfo' => 'setQueryUserinfo',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default' => 'getDefault',
        'comment' => 'getComment',
        'tfa' => 'getTfa',
        'type' => 'getType',
        'server1' => 'getServer1',
        'server2' => 'getServer2',
        'base_dn' => 'getBaseDn',
        'bind_dn' => 'getBindDn',
        'password' => 'getPassword',
        'user_attr' => 'getUserAttr',
        'port' => 'getPort',
        'secure' => 'getSecure',
        'sslversion' => 'getSslversion',
        'verify' => 'getVerify',
        'capath' => 'getCapath',
        'cert' => 'getCert',
        'certkey' => 'getCertkey',
        'filter' => 'getFilter',
        'sync_attributes' => 'getSyncAttributes',
        'user_classes' => 'getUserClasses',
        'group_dn' => 'getGroupDn',
        'group_name_attr' => 'getGroupNameAttr',
        'group_filter' => 'getGroupFilter',
        'group_classes' => 'getGroupClasses',
        'sync_defaults_options' => 'getSyncDefaultsOptions',
        'mode' => 'getMode',
        'case_sensitive' => 'getCaseSensitive',
        'domain' => 'getDomain',
        'issuer_url' => 'getIssuerUrl',
        'client_id' => 'getClientId',
        'client_key' => 'getClientKey',
        'autocreate' => 'getAutocreate',
        'username_claim' => 'getUsernameClaim',
        'groups_claim' => 'getGroupsClaim',
        'groups_autocreate' => 'getGroupsAutocreate',
        'groups_overwrite' => 'getGroupsOverwrite',
        'prompt' => 'getPrompt',
        'scopes' => 'getScopes',
        'acr_values' => 'getAcrValues',
        'query_userinfo' => 'getQueryUserinfo',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_PAM = 'pam';
    public const TYPE_PVE = 'pve';
    public const TYPE_LDAP = 'ldap';
    public const TYPE_AD = 'ad';
    public const TYPE_OPENID = 'openid';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_PAM,
            self::TYPE_PVE,
            self::TYPE_LDAP,
            self::TYPE_AD,
            self::TYPE_OPENID,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('default', $data ?? [], null);
        
        $this->setIfExists('comment', $data ?? [], null);
        
        $this->setIfExists('tfa', $data ?? [], null);
        
        $this->setIfExists('type', $data ?? [], null);
        
        $this->setIfExists('server1', $data ?? [], null);
        
        $this->setIfExists('server2', $data ?? [], null);
        
        $this->setIfExists('base_dn', $data ?? [], null);
        
        $this->setIfExists('bind_dn', $data ?? [], null);
        
        $this->setIfExists('password', $data ?? [], null);
        
        $this->setIfExists('user_attr', $data ?? [], null);
        
        $this->setIfExists('port', $data ?? [], null);
        
        $this->setIfExists('secure', $data ?? [], null);
        
        $this->setIfExists('sslversion', $data ?? [], null);
        
        $this->setIfExists('verify', $data ?? [], 0);
        
        $this->setIfExists('capath', $data ?? [], '/etc/ssl/certs');
        
        $this->setIfExists('cert', $data ?? [], null);
        
        $this->setIfExists('certkey', $data ?? [], null);
        
        $this->setIfExists('filter', $data ?? [], null);
        
        $this->setIfExists('sync_attributes', $data ?? [], null);
        
        $this->setIfExists('user_classes', $data ?? [], 'inetorgperson, posixaccount, person, user');
        
        $this->setIfExists('group_dn', $data ?? [], null);
        
        $this->setIfExists('group_name_attr', $data ?? [], null);
        
        $this->setIfExists('group_filter', $data ?? [], null);
        
        $this->setIfExists('group_classes', $data ?? [], 'groupOfNames, group, univentionGroup, ipausergroup');
        
        $this->setIfExists('sync_defaults_options', $data ?? [], null);
        
        $this->setIfExists('mode', $data ?? [], PveModeEnum::LDAP);
        
        $this->setIfExists('case_sensitive', $data ?? [], 1);
        
        $this->setIfExists('domain', $data ?? [], null);
        
        $this->setIfExists('issuer_url', $data ?? [], null);
        
        $this->setIfExists('client_id', $data ?? [], null);
        
        $this->setIfExists('client_key', $data ?? [], null);
        
        $this->setIfExists('autocreate', $data ?? [], 0);
        
        $this->setIfExists('username_claim', $data ?? [], null);
        
        $this->setIfExists('groups_claim', $data ?? [], null);
        
        $this->setIfExists('groups_autocreate', $data ?? [], 0);
        
        $this->setIfExists('groups_overwrite', $data ?? [], 0);
        
        $this->setIfExists('prompt', $data ?? [], null);
        
        $this->setIfExists('scopes', $data ?? [], 'email profile');
        
        $this->setIfExists('acr_values', $data ?? [], null);
        
        $this->setIfExists('query_userinfo', $data ?? [], 1);
        

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        if (!is_null($this->container['comment']) && (mb_strlen($this->container['comment']) > 4096)) {
            $invalidProperties[] = "invalid value for 'comment', the character length must be smaller than or equal to 4096.";
        }

        
        if (!is_null($this->container['tfa']) && (mb_strlen($this->container['tfa']) > 128)) {
            $invalidProperties[] = "invalid value for 'tfa', the character length must be smaller than or equal to 128.";
        }

        
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        
        if ($this->container['server1'] === null) {
            $invalidProperties[] = "'server1' can't be null";
        }
        if ((mb_strlen($this->container['server1']) > 256)) {
            $invalidProperties[] = "invalid value for 'server1', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/", $this->container['server1'])) {
            $invalidProperties[] = "invalid value for 'server1', must be conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/.";
        }

        
        if (!is_null($this->container['server2']) && (mb_strlen($this->container['server2']) > 256)) {
            $invalidProperties[] = "invalid value for 'server2', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['server2']) && !preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/", $this->container['server2'])) {
            $invalidProperties[] = "invalid value for 'server2', must be conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/.";
        }

        
        if ($this->container['base_dn'] === null) {
            $invalidProperties[] = "'base_dn' can't be null";
        }
        if ((mb_strlen($this->container['base_dn']) > 256)) {
            $invalidProperties[] = "invalid value for 'base_dn', the character length must be smaller than or equal to 256.";
        }

        
        if (!is_null($this->container['bind_dn']) && (mb_strlen($this->container['bind_dn']) > 256)) {
            $invalidProperties[] = "invalid value for 'bind_dn', the character length must be smaller than or equal to 256.";
        }

        
        
        if ($this->container['user_attr'] === null) {
            $invalidProperties[] = "'user_attr' can't be null";
        }
        if ((mb_strlen($this->container['user_attr']) > 256)) {
            $invalidProperties[] = "invalid value for 'user_attr', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/\\S{2,}/", $this->container['user_attr'])) {
            $invalidProperties[] = "invalid value for 'user_attr', must be conform to the pattern /\\S{2,}/.";
        }

        
        if (!is_null($this->container['port']) && ($this->container['port'] > 65535)) {
            $invalidProperties[] = "invalid value for 'port', must be smaller than or equal to 65535.";
        }

        if (!is_null($this->container['port']) && ($this->container['port'] < 1)) {
            $invalidProperties[] = "invalid value for 'port', must be bigger than or equal to 1.";
        }

        
        
        
        
        
        
        
        if (!is_null($this->container['filter']) && (mb_strlen($this->container['filter']) > 2048)) {
            $invalidProperties[] = "invalid value for 'filter', the character length must be smaller than or equal to 2048.";
        }

        
        if (!is_null($this->container['sync_attributes']) && !preg_match("/\\w+=[^,]+(,\\s*\\w+=[^,]+)*/", $this->container['sync_attributes'])) {
            $invalidProperties[] = "invalid value for 'sync_attributes', must be conform to the pattern /\\w+=[^,]+(,\\s*\\w+=[^,]+)*/.";
        }

        
        
        if (!is_null($this->container['group_dn']) && (mb_strlen($this->container['group_dn']) > 256)) {
            $invalidProperties[] = "invalid value for 'group_dn', the character length must be smaller than or equal to 256.";
        }

        
        if (!is_null($this->container['group_name_attr']) && (mb_strlen($this->container['group_name_attr']) > 256)) {
            $invalidProperties[] = "invalid value for 'group_name_attr', the character length must be smaller than or equal to 256.";
        }

        
        if (!is_null($this->container['group_filter']) && (mb_strlen($this->container['group_filter']) > 2048)) {
            $invalidProperties[] = "invalid value for 'group_filter', the character length must be smaller than or equal to 2048.";
        }

        
        
        
        
        
        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ((mb_strlen($this->container['domain']) > 256)) {
            $invalidProperties[] = "invalid value for 'domain', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/\\S+/", $this->container['domain'])) {
            $invalidProperties[] = "invalid value for 'domain', must be conform to the pattern /\\S+/.";
        }

        
        if ($this->container['issuer_url'] === null) {
            $invalidProperties[] = "'issuer_url' can't be null";
        }
        if ((mb_strlen($this->container['issuer_url']) > 256)) {
            $invalidProperties[] = "invalid value for 'issuer_url', the character length must be smaller than or equal to 256.";
        }

        
        if ($this->container['client_id'] === null) {
            $invalidProperties[] = "'client_id' can't be null";
        }
        if ((mb_strlen($this->container['client_id']) > 256)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be smaller than or equal to 256.";
        }

        
        if (!is_null($this->container['client_key']) && (mb_strlen($this->container['client_key']) > 256)) {
            $invalidProperties[] = "invalid value for 'client_key', the character length must be smaller than or equal to 256.";
        }

        
        
        
        if (!is_null($this->container['groups_claim']) && (mb_strlen($this->container['groups_claim']) > 256)) {
            $invalidProperties[] = "invalid value for 'groups_claim', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['groups_claim']) && !preg_match("/(?:[A-Za-z0-9\\.\\-_]+)/", $this->container['groups_claim'])) {
            $invalidProperties[] = "invalid value for 'groups_claim', must be conform to the pattern /(?:[A-Za-z0-9\\.\\-_]+)/.";
        }

        
        
        
        if (!is_null($this->container['prompt']) && !preg_match("/(?:none|login|consent|select_account|\\S+)/", $this->container['prompt'])) {
            $invalidProperties[] = "invalid value for 'prompt', must be conform to the pattern /(?:none|login|consent|select_account|\\S+)/.";
        }

        
        
        if (!is_null($this->container['acr_values']) && !preg_match("/^[^\\x00-\\x1F\\x7F <>#\\u0022]*$/", $this->container['acr_values'])) {
            $invalidProperties[] = "invalid value for 'acr_values', must be conform to the pattern /^[^\\x00-\\x1F\\x7F <>#\\u0022]*$/.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets default
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getDefault()
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $default Use this as default realm
     *
     * @return self
     */
    public function setDefault($default)
    {
        if (is_null($default)) {
            throw new \InvalidArgumentException('non-nullable default cannot be null');
        }
        $this->container['default'] = $default;

        return $this;
    }
    

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Description.
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        if ((mb_strlen($comment) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $comment when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 4096.');
        }

        $this->container['comment'] = $comment;

        return $this;
    }
    

    /**
     * Gets tfa
     *
     * @return string|null
     */
    public function getTfa()
    {
        return $this->container['tfa'];
    }

    /**
     * Sets tfa
     *
     * @param string|null $tfa Use Two-factor authentication.
     *
     * @return self
     */
    public function setTfa($tfa)
    {
        if (is_null($tfa)) {
            throw new \InvalidArgumentException('non-nullable tfa cannot be null');
        }
        if ((mb_strlen($tfa) > 128)) {
            throw new \InvalidArgumentException('invalid length for $tfa when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 128.');
        }

        $this->container['tfa'] = $tfa;

        return $this;
    }
    

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }
    

    /**
     * Gets server1
     *
     * @return string
     */
    public function getServer1()
    {
        return $this->container['server1'];
    }

    /**
     * Sets server1
     *
     * @param string $server1 Server IP address (or DNS name)
     *
     * @return self
     */
    public function setServer1($server1)
    {
        if (is_null($server1)) {
            throw new \InvalidArgumentException('non-nullable server1 cannot be null');
        }
        if ((mb_strlen($server1) > 256)) {
            throw new \InvalidArgumentException('invalid length for $server1 when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/", ObjectSerializer::toString($server1)))) {
            throw new \InvalidArgumentException("invalid value for \$server1 when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/.");
        }

        $this->container['server1'] = $server1;

        return $this;
    }
    

    /**
     * Gets server2
     *
     * @return string|null
     */
    public function getServer2()
    {
        return $this->container['server2'];
    }

    /**
     * Sets server2
     *
     * @param string|null $server2 Fallback Server IP address (or DNS name)
     *
     * @return self
     */
    public function setServer2($server2)
    {
        if (is_null($server2)) {
            throw new \InvalidArgumentException('non-nullable server2 cannot be null');
        }
        if ((mb_strlen($server2) > 256)) {
            throw new \InvalidArgumentException('invalid length for $server2 when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/", ObjectSerializer::toString($server2)))) {
            throw new \InvalidArgumentException("invalid value for \$server2 when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}|[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]*[A-Za-z0-9])?)*)$/.");
        }

        $this->container['server2'] = $server2;

        return $this;
    }
    

    /**
     * Gets base_dn
     *
     * @return string
     */
    public function getBaseDn()
    {
        return $this->container['base_dn'];
    }

    /**
     * Sets base_dn
     *
     * @param string $base_dn LDAP base domain name
     *
     * @return self
     */
    public function setBaseDn($base_dn)
    {
        if (is_null($base_dn)) {
            throw new \InvalidArgumentException('non-nullable base_dn cannot be null');
        }
        if ((mb_strlen($base_dn) > 256)) {
            throw new \InvalidArgumentException('invalid length for $base_dn when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['base_dn'] = $base_dn;

        return $this;
    }
    

    /**
     * Gets bind_dn
     *
     * @return string|null
     */
    public function getBindDn()
    {
        return $this->container['bind_dn'];
    }

    /**
     * Sets bind_dn
     *
     * @param string|null $bind_dn LDAP bind domain name
     *
     * @return self
     */
    public function setBindDn($bind_dn)
    {
        if (is_null($bind_dn)) {
            throw new \InvalidArgumentException('non-nullable bind_dn cannot be null');
        }
        if ((mb_strlen($bind_dn) > 256)) {
            throw new \InvalidArgumentException('invalid length for $bind_dn when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['bind_dn'] = $bind_dn;

        return $this;
    }
    

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password LDAP bind password. Will be stored in '/etc/pve/priv/realm/<REALM>.pw'.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }
    

    /**
     * Gets user_attr
     *
     * @return string
     */
    public function getUserAttr()
    {
        return $this->container['user_attr'];
    }

    /**
     * Sets user_attr
     *
     * @param string $user_attr LDAP user attribute name
     *
     * @return self
     */
    public function setUserAttr($user_attr)
    {
        if (is_null($user_attr)) {
            throw new \InvalidArgumentException('non-nullable user_attr cannot be null');
        }
        if ((mb_strlen($user_attr) > 256)) {
            throw new \InvalidArgumentException('invalid length for $user_attr when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/\\S{2,}/", ObjectSerializer::toString($user_attr)))) {
            throw new \InvalidArgumentException("invalid value for \$user_attr when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /\\S{2,}/.");
        }

        $this->container['user_attr'] = $user_attr;

        return $this;
    }
    

    /**
     * Gets port
     *
     * @return int|null
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int|null $port Server port.
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }

        if (($port > 65535)) {
            throw new \InvalidArgumentException('invalid value for $port when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 65535.');
        }
        if (($port < 1)) {
            throw new \InvalidArgumentException('invalid value for $port when calling AccessDomainsCreateDomainsRequest., must be bigger than or equal to 1.');
        }

        $this->container['port'] = $port;

        return $this;
    }
    

    /**
     * Gets secure
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getSecure()
    {
        return $this->container['secure'];
    }

    /**
     * Sets secure
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $secure Use secure LDAPS protocol. DEPRECATED: use 'mode' instead.
     *
     * @return self
     */
    public function setSecure($secure)
    {
        if (is_null($secure)) {
            throw new \InvalidArgumentException('non-nullable secure cannot be null');
        }
        $this->container['secure'] = $secure;

        return $this;
    }
    

    /**
     * Gets sslversion
     *
     * @return \ClientApi\PveClient\Model\PveSslversionEnum|null
     */
    public function getSslversion()
    {
        return $this->container['sslversion'];
    }

    /**
     * Sets sslversion
     *
     * @param \ClientApi\PveClient\Model\PveSslversionEnum|null $sslversion LDAPS TLS/SSL version. It's not recommended to use version older than 1.2!
     *
     * @return self
     */
    public function setSslversion($sslversion)
    {
        if (is_null($sslversion)) {
            throw new \InvalidArgumentException('non-nullable sslversion cannot be null');
        }
        $this->container['sslversion'] = $sslversion;

        return $this;
    }
    

    /**
     * Gets verify
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getVerify()
    {
        return $this->container['verify'];
    }

    /**
     * Sets verify
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $verify Verify the server's SSL certificate
     *
     * @return self
     */
    public function setVerify($verify)
    {
        if (is_null($verify)) {
            throw new \InvalidArgumentException('non-nullable verify cannot be null');
        }
        $this->container['verify'] = $verify;

        return $this;
    }
    

    /**
     * Gets capath
     *
     * @return string|null
     */
    public function getCapath()
    {
        return $this->container['capath'];
    }

    /**
     * Sets capath
     *
     * @param string|null $capath Path to the CA certificate store
     *
     * @return self
     */
    public function setCapath($capath)
    {
        if (is_null($capath)) {
            throw new \InvalidArgumentException('non-nullable capath cannot be null');
        }
        $this->container['capath'] = $capath;

        return $this;
    }
    

    /**
     * Gets cert
     *
     * @return string|null
     */
    public function getCert()
    {
        return $this->container['cert'];
    }

    /**
     * Sets cert
     *
     * @param string|null $cert Path to the client certificate
     *
     * @return self
     */
    public function setCert($cert)
    {
        if (is_null($cert)) {
            throw new \InvalidArgumentException('non-nullable cert cannot be null');
        }
        $this->container['cert'] = $cert;

        return $this;
    }
    

    /**
     * Gets certkey
     *
     * @return string|null
     */
    public function getCertkey()
    {
        return $this->container['certkey'];
    }

    /**
     * Sets certkey
     *
     * @param string|null $certkey Path to the client certificate key
     *
     * @return self
     */
    public function setCertkey($certkey)
    {
        if (is_null($certkey)) {
            throw new \InvalidArgumentException('non-nullable certkey cannot be null');
        }
        $this->container['certkey'] = $certkey;

        return $this;
    }
    

    /**
     * Gets filter
     *
     * @return string|null
     */
    public function getFilter()
    {
        return $this->container['filter'];
    }

    /**
     * Sets filter
     *
     * @param string|null $filter LDAP filter for user sync.
     *
     * @return self
     */
    public function setFilter($filter)
    {
        if (is_null($filter)) {
            throw new \InvalidArgumentException('non-nullable filter cannot be null');
        }
        if ((mb_strlen($filter) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $filter when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 2048.');
        }

        $this->container['filter'] = $filter;

        return $this;
    }
    

    /**
     * Gets sync_attributes
     *
     * @return string|null
     */
    public function getSyncAttributes()
    {
        return $this->container['sync_attributes'];
    }

    /**
     * Sets sync_attributes
     *
     * @param string|null $sync_attributes Comma separated list of key=value pairs for specifying which LDAP attributes map to which PVE user field. For example, to map the LDAP attribute 'mail' to PVEs 'email', write  'email=mail'. By default, each PVE user field is represented  by an LDAP attribute of the same name.
     *
     * @return self
     */
    public function setSyncAttributes($sync_attributes)
    {
        if (is_null($sync_attributes)) {
            throw new \InvalidArgumentException('non-nullable sync_attributes cannot be null');
        }

        if ((!preg_match("/\\w+=[^,]+(,\\s*\\w+=[^,]+)*/", ObjectSerializer::toString($sync_attributes)))) {
            throw new \InvalidArgumentException("invalid value for \$sync_attributes when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /\\w+=[^,]+(,\\s*\\w+=[^,]+)*/.");
        }

        $this->container['sync_attributes'] = $sync_attributes;

        return $this;
    }
    

    /**
     * Gets user_classes
     *
     * @return string|null
     */
    public function getUserClasses()
    {
        return $this->container['user_classes'];
    }

    /**
     * Sets user_classes
     *
     * @param string|null $user_classes The objectclasses for users.
     *
     * @return self
     */
    public function setUserClasses($user_classes)
    {
        if (is_null($user_classes)) {
            throw new \InvalidArgumentException('non-nullable user_classes cannot be null');
        }
        $this->container['user_classes'] = $user_classes;

        return $this;
    }
    

    /**
     * Gets group_dn
     *
     * @return string|null
     */
    public function getGroupDn()
    {
        return $this->container['group_dn'];
    }

    /**
     * Sets group_dn
     *
     * @param string|null $group_dn LDAP base domain name for group sync. If not set, the base_dn will be used.
     *
     * @return self
     */
    public function setGroupDn($group_dn)
    {
        if (is_null($group_dn)) {
            throw new \InvalidArgumentException('non-nullable group_dn cannot be null');
        }
        if ((mb_strlen($group_dn) > 256)) {
            throw new \InvalidArgumentException('invalid length for $group_dn when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['group_dn'] = $group_dn;

        return $this;
    }
    

    /**
     * Gets group_name_attr
     *
     * @return string|null
     */
    public function getGroupNameAttr()
    {
        return $this->container['group_name_attr'];
    }

    /**
     * Sets group_name_attr
     *
     * @param string|null $group_name_attr LDAP attribute representing a groups name. If not set or found, the first value of the DN will be used as name.
     *
     * @return self
     */
    public function setGroupNameAttr($group_name_attr)
    {
        if (is_null($group_name_attr)) {
            throw new \InvalidArgumentException('non-nullable group_name_attr cannot be null');
        }
        if ((mb_strlen($group_name_attr) > 256)) {
            throw new \InvalidArgumentException('invalid length for $group_name_attr when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['group_name_attr'] = $group_name_attr;

        return $this;
    }
    

    /**
     * Gets group_filter
     *
     * @return string|null
     */
    public function getGroupFilter()
    {
        return $this->container['group_filter'];
    }

    /**
     * Sets group_filter
     *
     * @param string|null $group_filter LDAP filter for group sync.
     *
     * @return self
     */
    public function setGroupFilter($group_filter)
    {
        if (is_null($group_filter)) {
            throw new \InvalidArgumentException('non-nullable group_filter cannot be null');
        }
        if ((mb_strlen($group_filter) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $group_filter when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 2048.');
        }

        $this->container['group_filter'] = $group_filter;

        return $this;
    }
    

    /**
     * Gets group_classes
     *
     * @return string|null
     */
    public function getGroupClasses()
    {
        return $this->container['group_classes'];
    }

    /**
     * Sets group_classes
     *
     * @param string|null $group_classes The objectclasses for groups.
     *
     * @return self
     */
    public function setGroupClasses($group_classes)
    {
        if (is_null($group_classes)) {
            throw new \InvalidArgumentException('non-nullable group_classes cannot be null');
        }
        $this->container['group_classes'] = $group_classes;

        return $this;
    }
    

    /**
     * Gets sync_defaults_options
     *
     * @return string|null
     */
    public function getSyncDefaultsOptions()
    {
        return $this->container['sync_defaults_options'];
    }

    /**
     * Sets sync_defaults_options
     *
     * @param string|null $sync_defaults_options The default options for behavior of synchronizations.
     *
     * @return self
     */
    public function setSyncDefaultsOptions($sync_defaults_options)
    {
        if (is_null($sync_defaults_options)) {
            throw new \InvalidArgumentException('non-nullable sync_defaults_options cannot be null');
        }
        $this->container['sync_defaults_options'] = $sync_defaults_options;

        return $this;
    }
    

    /**
     * Gets mode
     *
     * @return \ClientApi\PveClient\Model\PveModeEnum|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param \ClientApi\PveClient\Model\PveModeEnum|null $mode LDAP protocol mode.
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }
    

    /**
     * Gets case_sensitive
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getCaseSensitive()
    {
        return $this->container['case_sensitive'];
    }

    /**
     * Sets case_sensitive
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $case_sensitive username is case-sensitive
     *
     * @return self
     */
    public function setCaseSensitive($case_sensitive)
    {
        if (is_null($case_sensitive)) {
            throw new \InvalidArgumentException('non-nullable case_sensitive cannot be null');
        }
        $this->container['case_sensitive'] = $case_sensitive;

        return $this;
    }
    

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain AD domain name
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        if ((mb_strlen($domain) > 256)) {
            throw new \InvalidArgumentException('invalid length for $domain when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/\\S+/", ObjectSerializer::toString($domain)))) {
            throw new \InvalidArgumentException("invalid value for \$domain when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /\\S+/.");
        }

        $this->container['domain'] = $domain;

        return $this;
    }
    

    /**
     * Gets issuer_url
     *
     * @return string
     */
    public function getIssuerUrl()
    {
        return $this->container['issuer_url'];
    }

    /**
     * Sets issuer_url
     *
     * @param string $issuer_url OpenID Issuer Url
     *
     * @return self
     */
    public function setIssuerUrl($issuer_url)
    {
        if (is_null($issuer_url)) {
            throw new \InvalidArgumentException('non-nullable issuer_url cannot be null');
        }
        if ((mb_strlen($issuer_url) > 256)) {
            throw new \InvalidArgumentException('invalid length for $issuer_url when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['issuer_url'] = $issuer_url;

        return $this;
    }
    

    /**
     * Gets client_id
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string $client_id OpenID Client ID
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        if ((mb_strlen($client_id) > 256)) {
            throw new \InvalidArgumentException('invalid length for $client_id when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['client_id'] = $client_id;

        return $this;
    }
    

    /**
     * Gets client_key
     *
     * @return string|null
     */
    public function getClientKey()
    {
        return $this->container['client_key'];
    }

    /**
     * Sets client_key
     *
     * @param string|null $client_key OpenID Client Key
     *
     * @return self
     */
    public function setClientKey($client_key)
    {
        if (is_null($client_key)) {
            throw new \InvalidArgumentException('non-nullable client_key cannot be null');
        }
        if ((mb_strlen($client_key) > 256)) {
            throw new \InvalidArgumentException('invalid length for $client_key when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }

        $this->container['client_key'] = $client_key;

        return $this;
    }
    

    /**
     * Gets autocreate
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getAutocreate()
    {
        return $this->container['autocreate'];
    }

    /**
     * Sets autocreate
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $autocreate Automatically create users if they do not exist.
     *
     * @return self
     */
    public function setAutocreate($autocreate)
    {
        if (is_null($autocreate)) {
            throw new \InvalidArgumentException('non-nullable autocreate cannot be null');
        }
        $this->container['autocreate'] = $autocreate;

        return $this;
    }
    

    /**
     * Gets username_claim
     *
     * @return string|null
     */
    public function getUsernameClaim()
    {
        return $this->container['username_claim'];
    }

    /**
     * Sets username_claim
     *
     * @param string|null $username_claim OpenID claim used to generate the unique username.
     *
     * @return self
     */
    public function setUsernameClaim($username_claim)
    {
        if (is_null($username_claim)) {
            throw new \InvalidArgumentException('non-nullable username_claim cannot be null');
        }
        $this->container['username_claim'] = $username_claim;

        return $this;
    }
    

    /**
     * Gets groups_claim
     *
     * @return string|null
     */
    public function getGroupsClaim()
    {
        return $this->container['groups_claim'];
    }

    /**
     * Sets groups_claim
     *
     * @param string|null $groups_claim OpenID claim used to retrieve groups with.
     *
     * @return self
     */
    public function setGroupsClaim($groups_claim)
    {
        if (is_null($groups_claim)) {
            throw new \InvalidArgumentException('non-nullable groups_claim cannot be null');
        }
        if ((mb_strlen($groups_claim) > 256)) {
            throw new \InvalidArgumentException('invalid length for $groups_claim when calling AccessDomainsCreateDomainsRequest., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/(?:[A-Za-z0-9\\.\\-_]+)/", ObjectSerializer::toString($groups_claim)))) {
            throw new \InvalidArgumentException("invalid value for \$groups_claim when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /(?:[A-Za-z0-9\\.\\-_]+)/.");
        }

        $this->container['groups_claim'] = $groups_claim;

        return $this;
    }
    

    /**
     * Gets groups_autocreate
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getGroupsAutocreate()
    {
        return $this->container['groups_autocreate'];
    }

    /**
     * Sets groups_autocreate
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $groups_autocreate Automatically create groups if they do not exist.
     *
     * @return self
     */
    public function setGroupsAutocreate($groups_autocreate)
    {
        if (is_null($groups_autocreate)) {
            throw new \InvalidArgumentException('non-nullable groups_autocreate cannot be null');
        }
        $this->container['groups_autocreate'] = $groups_autocreate;

        return $this;
    }
    

    /**
     * Gets groups_overwrite
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getGroupsOverwrite()
    {
        return $this->container['groups_overwrite'];
    }

    /**
     * Sets groups_overwrite
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $groups_overwrite All groups will be overwritten for the user on login.
     *
     * @return self
     */
    public function setGroupsOverwrite($groups_overwrite)
    {
        if (is_null($groups_overwrite)) {
            throw new \InvalidArgumentException('non-nullable groups_overwrite cannot be null');
        }
        $this->container['groups_overwrite'] = $groups_overwrite;

        return $this;
    }
    

    /**
     * Gets prompt
     *
     * @return string|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string|null $prompt Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }

        if ((!preg_match("/(?:none|login|consent|select_account|\\S+)/", ObjectSerializer::toString($prompt)))) {
            throw new \InvalidArgumentException("invalid value for \$prompt when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /(?:none|login|consent|select_account|\\S+)/.");
        }

        $this->container['prompt'] = $prompt;

        return $this;
    }
    

    /**
     * Gets scopes
     *
     * @return string|null
     */
    public function getScopes()
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param string|null $scopes Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.
     *
     * @return self
     */
    public function setScopes($scopes)
    {
        if (is_null($scopes)) {
            throw new \InvalidArgumentException('non-nullable scopes cannot be null');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }
    

    /**
     * Gets acr_values
     *
     * @return string|null
     */
    public function getAcrValues()
    {
        return $this->container['acr_values'];
    }

    /**
     * Sets acr_values
     *
     * @param string|null $acr_values Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.
     *
     * @return self
     */
    public function setAcrValues($acr_values)
    {
        if (is_null($acr_values)) {
            throw new \InvalidArgumentException('non-nullable acr_values cannot be null');
        }

        if ((!preg_match("/^[^\\x00-\\x1F\\x7F <>#\\u0022]*$/", ObjectSerializer::toString($acr_values)))) {
            throw new \InvalidArgumentException("invalid value for \$acr_values when calling AccessDomainsCreateDomainsRequest., must conform to the pattern /^[^\\x00-\\x1F\\x7F <>#\\u0022]*$/.");
        }

        $this->container['acr_values'] = $acr_values;

        return $this;
    }
    

    /**
     * Gets query_userinfo
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getQueryUserinfo()
    {
        return $this->container['query_userinfo'];
    }

    /**
     * Sets query_userinfo
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $query_userinfo Enables querying the userinfo endpoint for claims values.
     *
     * @return self
     */
    public function setQueryUserinfo($query_userinfo)
    {
        if (is_null($query_userinfo)) {
            throw new \InvalidArgumentException('non-nullable query_userinfo cannot be null');
        }
        $this->container['query_userinfo'] = $query_userinfo;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



