<?php
/**
 * ClusterConfigJoinRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * ClusterConfigJoinRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClusterConfigJoinRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClusterConfigJoinRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'fingerprint' => 'string',
        'force' => '\ClientApi\PveClient\Model\PveBoolean',
        'hostname' => 'string',
        'nodeid' => 'int',
        'password' => 'string',
        'votes' => 'int',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'fingerprint' => null,
        'force' => null,
        'hostname' => null,
        'nodeid' => 'int64',
        'password' => null,
        'votes' => 'int64',
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'fingerprint' => false,
        'force' => false,
        'hostname' => false,
        'nodeid' => false,
        'password' => false,
        'votes' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fingerprint' => 'fingerprint',
        'force' => 'force',
        'hostname' => 'hostname',
        'nodeid' => 'nodeid',
        'password' => 'password',
        'votes' => 'votes',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fingerprint' => 'setFingerprint',
        'force' => 'setForce',
        'hostname' => 'setHostname',
        'nodeid' => 'setNodeid',
        'password' => 'setPassword',
        'votes' => 'setVotes',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fingerprint' => 'getFingerprint',
        'force' => 'getForce',
        'hostname' => 'getHostname',
        'nodeid' => 'getNodeid',
        'password' => 'getPassword',
        'votes' => 'getVotes',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('fingerprint', $data ?? [], null);
        
        $this->setIfExists('force', $data ?? [], null);
        
        $this->setIfExists('hostname', $data ?? [], null);
        
        $this->setIfExists('nodeid', $data ?? [], null);
        
        $this->setIfExists('password', $data ?? [], null);
        
        $this->setIfExists('votes', $data ?? [], null);
        

        $this->_loadIndexedFamilies($data ?? []);

    }


    /** Bucket indexed-family wire keys into $container. Called from __construct
     *  and from ObjectSerializer::deserialize (via our post-loop hook). */
    public function _loadIndexedFamilies($data): void
    {
        $entries = is_object($data) ? get_object_vars($data) : (array) $data;
        foreach ($entries as $key => $value) {
            if (preg_match('/^link(\d+)$/', (string) $key, $m)) {
                $idx = (int) $m[1];
                if ($idx >= 0 && $idx <= 7) {
                    $this->container[(string) $key] = $value;
                }
                continue;
            }
        }
    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if ($this->container['fingerprint'] === null) {
            $invalidProperties[] = "'fingerprint' can't be null";
        }
        if (!preg_match("/([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/", $this->container['fingerprint'])) {
            $invalidProperties[] = "invalid value for 'fingerprint', must be conform to the pattern /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/.";
        }

        
        
        if ($this->container['hostname'] === null) {
            $invalidProperties[] = "'hostname' can't be null";
        }
        
        if (!is_null($this->container['nodeid']) && ($this->container['nodeid'] < 1)) {
            $invalidProperties[] = "invalid value for 'nodeid', must be bigger than or equal to 1.";
        }

        
        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        if ((mb_strlen($this->container['password']) > 128)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 128.";
        }

        
        if (!is_null($this->container['votes']) && ($this->container['votes'] < 0)) {
            $invalidProperties[] = "invalid value for 'votes', must be bigger than or equal to 0.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets fingerprint
     *
     * @return string
     */
    public function getFingerprint()
    {
        return $this->container['fingerprint'];
    }

    /**
     * Sets fingerprint
     *
     * @param string $fingerprint Certificate SHA 256 fingerprint.
     *
     * @return self
     */
    public function setFingerprint($fingerprint)
    {
        if (is_null($fingerprint)) {
            throw new \InvalidArgumentException('non-nullable fingerprint cannot be null');
        }

        if ((!preg_match("/([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/", ObjectSerializer::toString($fingerprint)))) {
            throw new \InvalidArgumentException("invalid value for \$fingerprint when calling ClusterConfigJoinRequest., must conform to the pattern /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/.");
        }

        $this->container['fingerprint'] = $fingerprint;

        return $this;
    }
    

    /**
     * Gets force
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getForce()
    {
        return $this->container['force'];
    }

    /**
     * Sets force
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $force Do not throw error if node already exists.
     *
     * @return self
     */
    public function setForce($force)
    {
        if (is_null($force)) {
            throw new \InvalidArgumentException('non-nullable force cannot be null');
        }
        $this->container['force'] = $force;

        return $this;
    }
    

    /**
     * Gets hostname
     *
     * @return string
     */
    public function getHostname()
    {
        return $this->container['hostname'];
    }

    /**
     * Sets hostname
     *
     * @param string $hostname Hostname (or IP) of an existing cluster member.
     *
     * @return self
     */
    public function setHostname($hostname)
    {
        if (is_null($hostname)) {
            throw new \InvalidArgumentException('non-nullable hostname cannot be null');
        }
        $this->container['hostname'] = $hostname;

        return $this;
    }
    

    /**
     * Gets nodeid
     *
     * @return int|null
     */
    public function getNodeid()
    {
        return $this->container['nodeid'];
    }

    /**
     * Sets nodeid
     *
     * @param int|null $nodeid Node id for this node.
     *
     * @return self
     */
    public function setNodeid($nodeid)
    {
        if (is_null($nodeid)) {
            throw new \InvalidArgumentException('non-nullable nodeid cannot be null');
        }

        if (($nodeid < 1)) {
            throw new \InvalidArgumentException('invalid value for $nodeid when calling ClusterConfigJoinRequest., must be bigger than or equal to 1.');
        }

        $this->container['nodeid'] = $nodeid;

        return $this;
    }
    

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password Superuser (root) password of peer node.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        if ((mb_strlen($password) > 128)) {
            throw new \InvalidArgumentException('invalid length for $password when calling ClusterConfigJoinRequest., must be smaller than or equal to 128.');
        }

        $this->container['password'] = $password;

        return $this;
    }
    

    /**
     * Gets votes
     *
     * @return int|null
     */
    public function getVotes()
    {
        return $this->container['votes'];
    }

    /**
     * Sets votes
     *
     * @param int|null $votes Number of votes for this node
     *
     * @return self
     */
    public function setVotes($votes)
    {
        if (is_null($votes)) {
            throw new \InvalidArgumentException('non-nullable votes cannot be null');
        }

        if (($votes < 0)) {
            throw new \InvalidArgumentException('invalid value for $votes when calling ClusterConfigJoinRequest., must be bigger than or equal to 0.');
        }

        $this->container['votes'] = $votes;

        return $this;
    }
    


    /** Routes per-index getNet0/setNet0/... calls into $container. */
    public function __call(string $name, array $arguments)
    {

        if (preg_match('/^(get|set)Link(\d+)$/', $name, $m)) {
            $verb = $m[1];
            $idx = (int) $m[2];
            if ($idx >= 0 && $idx <= 7) {
                $key = 'link' . $idx;
                if ($verb === 'get') {
                    return $this->container[$key] ?? null;
                }
                $this->container[$key] = $arguments[0] ?? null;
                return $this;
            }
        }

        throw new \BadMethodCallException(sprintf(
            'Call to undefined method %s::%s()',
            static::class,
            $name,
        ));
    }


    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);

        // Inject indexed-family wire keys (kept in $container, hidden from $openAPITypes).
        if (is_object($out)) {

            for ($_i = 0; $_i <= 7; $_i++) {
                $_k = 'link' . $_i;
                if (array_key_exists($_k, $this->container) && $this->container[$_k] !== null) {
                    $out->{$_k} = $this->container[$_k];
                }
            }

        }

        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
    /** @return array<int, mixed> links family as `[index => value]`. */
    public function getLinks(): array
    {
        $out = [];
        for ($i = 0; $i <= 7; $i++) {
            $key = 'link' . $i;
            if (array_key_exists($key, $this->container) && $this->container[$key] !== null) {
                $out[$i] = $this->container[$key];
            }
        }
        return $out;
    }

    /** Replace the links family. Out-of-range indices (0..7) silently skipped.
     *  @param array<int, mixed> $items */
    public function setLinks(array $items): self
    {
        for ($i = 0; $i <= 7; $i++) {
            unset($this->container['link' . $i]);
        }
        foreach ($items as $idx => $val) {
            $idx = (int) $idx;
            if ($idx >= 0 && $idx <= 7) {
                $this->container['link' . $idx] = $val;
            }
        }
        return $this;
    }
}



