<?php
/**
 * ClusterResourcesResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * ClusterResourcesResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClusterResourcesResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClusterResourcesResponse_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'cgroup_mode' => 'int',
        'content' => 'string',
        'cpu' => 'float',
        'disk' => 'int',
        'diskread' => 'int',
        'diskwrite' => 'int',
        'hastate' => 'string',
        'id' => 'string',
        'level' => 'string',
        'lock' => 'string',
        'maxcpu' => 'float',
        'maxdisk' => 'int',
        'maxmem' => 'int',
        'mem' => 'int',
        'memhost' => 'int',
        'name' => 'string',
        'netin' => 'int',
        'netout' => 'int',
        'network' => 'string',
        'network_type' => '\ClientApi\PveClient\Model\PveClusterNetworkTypeEnum',
        'node' => 'string',
        'plugintype' => 'string',
        'pool' => 'string',
        'protocol' => 'string',
        'sdn' => 'string',
        'status' => 'string',
        'storage' => 'string',
        'tags' => 'string',
        'template' => '\ClientApi\PveClient\Model\PveBoolean',
        'type' => '\ClientApi\PveClient\Model\PveClusterTypeEnum2',
        'uptime' => 'int',
        'vmid' => 'int',
        'zone_type' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'cgroup_mode' => 'int64',
        'content' => 'pve-storage-content-list',
        'cpu' => null,
        'disk' => 'int64',
        'diskread' => 'int64',
        'diskwrite' => 'int64',
        'hastate' => null,
        'id' => null,
        'level' => null,
        'lock' => null,
        'maxcpu' => null,
        'maxdisk' => 'int64',
        'maxmem' => 'int64',
        'mem' => 'int64',
        'memhost' => 'int64',
        'name' => null,
        'netin' => 'int64',
        'netout' => 'int64',
        'network' => null,
        'network_type' => null,
        'node' => 'pve-node',
        'plugintype' => null,
        'pool' => null,
        'protocol' => null,
        'sdn' => null,
        'status' => null,
        'storage' => 'pve-storage-id',
        'tags' => null,
        'template' => null,
        'type' => null,
        'uptime' => 'int64',
        'vmid' => 'pve-vmid',
        'zone_type' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'cgroup_mode' => false,
        'content' => false,
        'cpu' => false,
        'disk' => false,
        'diskread' => false,
        'diskwrite' => false,
        'hastate' => false,
        'id' => false,
        'level' => false,
        'lock' => false,
        'maxcpu' => false,
        'maxdisk' => false,
        'maxmem' => false,
        'mem' => false,
        'memhost' => false,
        'name' => false,
        'netin' => false,
        'netout' => false,
        'network' => false,
        'network_type' => false,
        'node' => false,
        'plugintype' => false,
        'pool' => false,
        'protocol' => false,
        'sdn' => false,
        'status' => false,
        'storage' => false,
        'tags' => false,
        'template' => false,
        'type' => false,
        'uptime' => false,
        'vmid' => false,
        'zone_type' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cgroup_mode' => 'cgroup-mode',
        'content' => 'content',
        'cpu' => 'cpu',
        'disk' => 'disk',
        'diskread' => 'diskread',
        'diskwrite' => 'diskwrite',
        'hastate' => 'hastate',
        'id' => 'id',
        'level' => 'level',
        'lock' => 'lock',
        'maxcpu' => 'maxcpu',
        'maxdisk' => 'maxdisk',
        'maxmem' => 'maxmem',
        'mem' => 'mem',
        'memhost' => 'memhost',
        'name' => 'name',
        'netin' => 'netin',
        'netout' => 'netout',
        'network' => 'network',
        'network_type' => 'network-type',
        'node' => 'node',
        'plugintype' => 'plugintype',
        'pool' => 'pool',
        'protocol' => 'protocol',
        'sdn' => 'sdn',
        'status' => 'status',
        'storage' => 'storage',
        'tags' => 'tags',
        'template' => 'template',
        'type' => 'type',
        'uptime' => 'uptime',
        'vmid' => 'vmid',
        'zone_type' => 'zone-type',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cgroup_mode' => 'setCgroupMode',
        'content' => 'setContent',
        'cpu' => 'setCpu',
        'disk' => 'setDisk',
        'diskread' => 'setDiskread',
        'diskwrite' => 'setDiskwrite',
        'hastate' => 'setHastate',
        'id' => 'setId',
        'level' => 'setLevel',
        'lock' => 'setLock',
        'maxcpu' => 'setMaxcpu',
        'maxdisk' => 'setMaxdisk',
        'maxmem' => 'setMaxmem',
        'mem' => 'setMem',
        'memhost' => 'setMemhost',
        'name' => 'setName',
        'netin' => 'setNetin',
        'netout' => 'setNetout',
        'network' => 'setNetwork',
        'network_type' => 'setNetworkType',
        'node' => 'setNode',
        'plugintype' => 'setPlugintype',
        'pool' => 'setPool',
        'protocol' => 'setProtocol',
        'sdn' => 'setSdn',
        'status' => 'setStatus',
        'storage' => 'setStorage',
        'tags' => 'setTags',
        'template' => 'setTemplate',
        'type' => 'setType',
        'uptime' => 'setUptime',
        'vmid' => 'setVmid',
        'zone_type' => 'setZoneType',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cgroup_mode' => 'getCgroupMode',
        'content' => 'getContent',
        'cpu' => 'getCpu',
        'disk' => 'getDisk',
        'diskread' => 'getDiskread',
        'diskwrite' => 'getDiskwrite',
        'hastate' => 'getHastate',
        'id' => 'getId',
        'level' => 'getLevel',
        'lock' => 'getLock',
        'maxcpu' => 'getMaxcpu',
        'maxdisk' => 'getMaxdisk',
        'maxmem' => 'getMaxmem',
        'mem' => 'getMem',
        'memhost' => 'getMemhost',
        'name' => 'getName',
        'netin' => 'getNetin',
        'netout' => 'getNetout',
        'network' => 'getNetwork',
        'network_type' => 'getNetworkType',
        'node' => 'getNode',
        'plugintype' => 'getPlugintype',
        'pool' => 'getPool',
        'protocol' => 'getProtocol',
        'sdn' => 'getSdn',
        'status' => 'getStatus',
        'storage' => 'getStorage',
        'tags' => 'getTags',
        'template' => 'getTemplate',
        'type' => 'getType',
        'uptime' => 'getUptime',
        'vmid' => 'getVmid',
        'zone_type' => 'getZoneType',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('cgroup_mode', $data ?? [], null);
        
        $this->setIfExists('content', $data ?? [], null);
        
        $this->setIfExists('cpu', $data ?? [], null);
        
        $this->setIfExists('disk', $data ?? [], null);
        
        $this->setIfExists('diskread', $data ?? [], null);
        
        $this->setIfExists('diskwrite', $data ?? [], null);
        
        $this->setIfExists('hastate', $data ?? [], null);
        
        $this->setIfExists('id', $data ?? [], null);
        
        $this->setIfExists('level', $data ?? [], null);
        
        $this->setIfExists('lock', $data ?? [], null);
        
        $this->setIfExists('maxcpu', $data ?? [], null);
        
        $this->setIfExists('maxdisk', $data ?? [], null);
        
        $this->setIfExists('maxmem', $data ?? [], null);
        
        $this->setIfExists('mem', $data ?? [], null);
        
        $this->setIfExists('memhost', $data ?? [], null);
        
        $this->setIfExists('name', $data ?? [], null);
        
        $this->setIfExists('netin', $data ?? [], null);
        
        $this->setIfExists('netout', $data ?? [], null);
        
        $this->setIfExists('network', $data ?? [], null);
        
        $this->setIfExists('network_type', $data ?? [], null);
        
        $this->setIfExists('node', $data ?? [], null);
        
        $this->setIfExists('plugintype', $data ?? [], null);
        
        $this->setIfExists('pool', $data ?? [], null);
        
        $this->setIfExists('protocol', $data ?? [], null);
        
        $this->setIfExists('sdn', $data ?? [], null);
        
        $this->setIfExists('status', $data ?? [], null);
        
        $this->setIfExists('storage', $data ?? [], null);
        
        $this->setIfExists('tags', $data ?? [], null);
        
        $this->setIfExists('template', $data ?? [], 0);
        
        $this->setIfExists('type', $data ?? [], null);
        
        $this->setIfExists('uptime', $data ?? [], null);
        
        $this->setIfExists('vmid', $data ?? [], null);
        
        $this->setIfExists('zone_type', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        if (!is_null($this->container['cpu']) && ($this->container['cpu'] < 0)) {
            $invalidProperties[] = "invalid value for 'cpu', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['disk']) && ($this->container['disk'] < 0)) {
            $invalidProperties[] = "invalid value for 'disk', must be bigger than or equal to 0.";
        }

        
        
        
        
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        
        
        
        if (!is_null($this->container['maxcpu']) && ($this->container['maxcpu'] < 0)) {
            $invalidProperties[] = "invalid value for 'maxcpu', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['maxdisk']) && ($this->container['maxdisk'] < 0)) {
            $invalidProperties[] = "invalid value for 'maxdisk', must be bigger than or equal to 0.";
        }

        
        
        if (!is_null($this->container['mem']) && ($this->container['mem'] < 0)) {
            $invalidProperties[] = "invalid value for 'mem', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['memhost']) && ($this->container['memhost'] < 0)) {
            $invalidProperties[] = "invalid value for 'memhost', must be bigger than or equal to 0.";
        }

        
        
        
        
        
        
        if (!is_null($this->container['node']) && !preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $this->container['node'])) {
            $invalidProperties[] = "invalid value for 'node', must be conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.";
        }

        
        
        
        
        
        
        if (!is_null($this->container['storage']) && !preg_match("/^[a-z][a-z0-9\\-_.]*[a-z0-9]$/", $this->container['storage'])) {
            $invalidProperties[] = "invalid value for 'storage', must be conform to the pattern /^[a-z][a-z0-9\\-_.]*[a-z0-9]$/.";
        }

        
        
        
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        
        
        if (!is_null($this->container['vmid']) && ($this->container['vmid'] > 999999999)) {
            $invalidProperties[] = "invalid value for 'vmid', must be smaller than or equal to 999999999.";
        }

        if (!is_null($this->container['vmid']) && ($this->container['vmid'] < 100)) {
            $invalidProperties[] = "invalid value for 'vmid', must be bigger than or equal to 100.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets cgroup_mode
     *
     * @return int|null
     */
    public function getCgroupMode()
    {
        return $this->container['cgroup_mode'];
    }

    /**
     * Sets cgroup_mode
     *
     * @param int|null $cgroup_mode The cgroup mode the node operates under (for type 'node').
     *
     * @return self
     */
    public function setCgroupMode($cgroup_mode)
    {
        if (is_null($cgroup_mode)) {
            throw new \InvalidArgumentException('non-nullable cgroup_mode cannot be null');
        }
        $this->container['cgroup_mode'] = $cgroup_mode;

        return $this;
    }
    

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content Allowed storage content types (for type 'storage').
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }
    

    /**
     * Gets cpu
     *
     * @return float|null
     */
    public function getCpu()
    {
        return $this->container['cpu'];
    }

    /**
     * Sets cpu
     *
     * @param float|null $cpu CPU utilization (for types 'node', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setCpu($cpu)
    {
        if (is_null($cpu)) {
            throw new \InvalidArgumentException('non-nullable cpu cannot be null');
        }

        if (($cpu < 0)) {
            throw new \InvalidArgumentException('invalid value for $cpu when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['cpu'] = $cpu;

        return $this;
    }
    

    /**
     * Gets disk
     *
     * @return int|null
     */
    public function getDisk()
    {
        return $this->container['disk'];
    }

    /**
     * Sets disk
     *
     * @param int|null $disk Used disk space in bytes (for type 'storage'), used root image space for VMs (for types 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setDisk($disk)
    {
        if (is_null($disk)) {
            throw new \InvalidArgumentException('non-nullable disk cannot be null');
        }

        if (($disk < 0)) {
            throw new \InvalidArgumentException('invalid value for $disk when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['disk'] = $disk;

        return $this;
    }
    

    /**
     * Gets diskread
     *
     * @return int|null
     */
    public function getDiskread()
    {
        return $this->container['diskread'];
    }

    /**
     * Sets diskread
     *
     * @param int|null $diskread The number of bytes the guest read from its block devices since the guest was started. This info is not available for all storage types. (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setDiskread($diskread)
    {
        if (is_null($diskread)) {
            throw new \InvalidArgumentException('non-nullable diskread cannot be null');
        }
        $this->container['diskread'] = $diskread;

        return $this;
    }
    

    /**
     * Gets diskwrite
     *
     * @return int|null
     */
    public function getDiskwrite()
    {
        return $this->container['diskwrite'];
    }

    /**
     * Sets diskwrite
     *
     * @param int|null $diskwrite The number of bytes the guest wrote to its block devices since the guest was started. This info is not available for all storage types. (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setDiskwrite($diskwrite)
    {
        if (is_null($diskwrite)) {
            throw new \InvalidArgumentException('non-nullable diskwrite cannot be null');
        }
        $this->container['diskwrite'] = $diskwrite;

        return $this;
    }
    

    /**
     * Gets hastate
     *
     * @return string|null
     */
    public function getHastate()
    {
        return $this->container['hastate'];
    }

    /**
     * Sets hastate
     *
     * @param string|null $hastate HA service status (for HA managed VMs).
     *
     * @return self
     */
    public function setHastate($hastate)
    {
        if (is_null($hastate)) {
            throw new \InvalidArgumentException('non-nullable hastate cannot be null');
        }
        $this->container['hastate'] = $hastate;

        return $this;
    }
    

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Resource id.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    

    /**
     * Gets level
     *
     * @return string|null
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param string|null $level Support level (for type 'node').
     *
     * @return self
     */
    public function setLevel($level)
    {
        if (is_null($level)) {
            throw new \InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }
    

    /**
     * Gets lock
     *
     * @return string|null
     */
    public function getLock()
    {
        return $this->container['lock'];
    }

    /**
     * Sets lock
     *
     * @param string|null $lock The guest's current config lock (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setLock($lock)
    {
        if (is_null($lock)) {
            throw new \InvalidArgumentException('non-nullable lock cannot be null');
        }
        $this->container['lock'] = $lock;

        return $this;
    }
    

    /**
     * Gets maxcpu
     *
     * @return float|null
     */
    public function getMaxcpu()
    {
        return $this->container['maxcpu'];
    }

    /**
     * Sets maxcpu
     *
     * @param float|null $maxcpu Number of available CPUs (for types 'node', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setMaxcpu($maxcpu)
    {
        if (is_null($maxcpu)) {
            throw new \InvalidArgumentException('non-nullable maxcpu cannot be null');
        }

        if (($maxcpu < 0)) {
            throw new \InvalidArgumentException('invalid value for $maxcpu when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['maxcpu'] = $maxcpu;

        return $this;
    }
    

    /**
     * Gets maxdisk
     *
     * @return int|null
     */
    public function getMaxdisk()
    {
        return $this->container['maxdisk'];
    }

    /**
     * Sets maxdisk
     *
     * @param int|null $maxdisk Storage size in bytes (for type 'storage'), root image size for VMs (for types 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setMaxdisk($maxdisk)
    {
        if (is_null($maxdisk)) {
            throw new \InvalidArgumentException('non-nullable maxdisk cannot be null');
        }

        if (($maxdisk < 0)) {
            throw new \InvalidArgumentException('invalid value for $maxdisk when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['maxdisk'] = $maxdisk;

        return $this;
    }
    

    /**
     * Gets maxmem
     *
     * @return int|null
     */
    public function getMaxmem()
    {
        return $this->container['maxmem'];
    }

    /**
     * Sets maxmem
     *
     * @param int|null $maxmem Number of available memory in bytes (for types 'node', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setMaxmem($maxmem)
    {
        if (is_null($maxmem)) {
            throw new \InvalidArgumentException('non-nullable maxmem cannot be null');
        }
        $this->container['maxmem'] = $maxmem;

        return $this;
    }
    

    /**
     * Gets mem
     *
     * @return int|null
     */
    public function getMem()
    {
        return $this->container['mem'];
    }

    /**
     * Sets mem
     *
     * @param int|null $mem Used memory in bytes (for types 'node', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setMem($mem)
    {
        if (is_null($mem)) {
            throw new \InvalidArgumentException('non-nullable mem cannot be null');
        }

        if (($mem < 0)) {
            throw new \InvalidArgumentException('invalid value for $mem when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['mem'] = $mem;

        return $this;
    }
    

    /**
     * Gets memhost
     *
     * @return int|null
     */
    public function getMemhost()
    {
        return $this->container['memhost'];
    }

    /**
     * Sets memhost
     *
     * @param int|null $memhost Used memory in bytes from the point of view of the host (for types 'qemu').
     *
     * @return self
     */
    public function setMemhost($memhost)
    {
        if (is_null($memhost)) {
            throw new \InvalidArgumentException('non-nullable memhost cannot be null');
        }

        if (($memhost < 0)) {
            throw new \InvalidArgumentException('invalid value for $memhost when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['memhost'] = $memhost;

        return $this;
    }
    

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of the resource.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }
    

    /**
     * Gets netin
     *
     * @return int|null
     */
    public function getNetin()
    {
        return $this->container['netin'];
    }

    /**
     * Sets netin
     *
     * @param int|null $netin The amount of traffic in bytes that was sent to the guest over the network since it was started. (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setNetin($netin)
    {
        if (is_null($netin)) {
            throw new \InvalidArgumentException('non-nullable netin cannot be null');
        }
        $this->container['netin'] = $netin;

        return $this;
    }
    

    /**
     * Gets netout
     *
     * @return int|null
     */
    public function getNetout()
    {
        return $this->container['netout'];
    }

    /**
     * Sets netout
     *
     * @param int|null $netout The amount of traffic in bytes that was sent from the guest over the network since it was started. (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setNetout($netout)
    {
        if (is_null($netout)) {
            throw new \InvalidArgumentException('non-nullable netout cannot be null');
        }
        $this->container['netout'] = $netout;

        return $this;
    }
    

    /**
     * Gets network
     *
     * @return string|null
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string|null $network The name of a Network entity (for type 'network').
     *
     * @return self
     */
    public function setNetwork($network)
    {
        if (is_null($network)) {
            throw new \InvalidArgumentException('non-nullable network cannot be null');
        }
        $this->container['network'] = $network;

        return $this;
    }
    

    /**
     * Gets network_type
     *
     * @return \ClientApi\PveClient\Model\PveClusterNetworkTypeEnum|null
     */
    public function getNetworkType()
    {
        return $this->container['network_type'];
    }

    /**
     * Sets network_type
     *
     * @param \ClientApi\PveClient\Model\PveClusterNetworkTypeEnum|null $network_type The type of network resource (for type 'network').
     *
     * @return self
     */
    public function setNetworkType($network_type)
    {
        if (is_null($network_type)) {
            throw new \InvalidArgumentException('non-nullable network_type cannot be null');
        }
        $this->container['network_type'] = $network_type;

        return $this;
    }
    

    /**
     * Gets node
     *
     * @return string|null
     */
    public function getNode()
    {
        return $this->container['node'];
    }

    /**
     * Sets node
     *
     * @param string|null $node The cluster node name (for types 'node', 'storage', 'qemu', and 'lxc').
     *
     * @return self
     */
    public function setNode($node)
    {
        if (is_null($node)) {
            throw new \InvalidArgumentException('non-nullable node cannot be null');
        }

        if ((!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", ObjectSerializer::toString($node)))) {
            throw new \InvalidArgumentException("invalid value for \$node when calling ClusterResourcesResponseDataInner., must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }

        $this->container['node'] = $node;

        return $this;
    }
    

    /**
     * Gets plugintype
     *
     * @return string|null
     */
    public function getPlugintype()
    {
        return $this->container['plugintype'];
    }

    /**
     * Sets plugintype
     *
     * @param string|null $plugintype More specific type, if available.
     *
     * @return self
     */
    public function setPlugintype($plugintype)
    {
        if (is_null($plugintype)) {
            throw new \InvalidArgumentException('non-nullable plugintype cannot be null');
        }
        $this->container['plugintype'] = $plugintype;

        return $this;
    }
    

    /**
     * Gets pool
     *
     * @return string|null
     */
    public function getPool()
    {
        return $this->container['pool'];
    }

    /**
     * Sets pool
     *
     * @param string|null $pool The pool name (for types 'pool', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setPool($pool)
    {
        if (is_null($pool)) {
            throw new \InvalidArgumentException('non-nullable pool cannot be null');
        }
        $this->container['pool'] = $pool;

        return $this;
    }
    

    /**
     * Gets protocol
     *
     * @return string|null
     */
    public function getProtocol()
    {
        return $this->container['protocol'];
    }

    /**
     * Sets protocol
     *
     * @param string|null $protocol The protocol of a fabric (for type 'network', network-type 'fabric').
     *
     * @return self
     */
    public function setProtocol($protocol)
    {
        if (is_null($protocol)) {
            throw new \InvalidArgumentException('non-nullable protocol cannot be null');
        }
        $this->container['protocol'] = $protocol;

        return $this;
    }
    

    /**
     * Gets sdn
     *
     * @return string|null
     */
    public function getSdn()
    {
        return $this->container['sdn'];
    }

    /**
     * Sets sdn
     *
     * @param string|null $sdn The name of an SDN entity (for type 'sdn')
     *
     * @return self
     */
    public function setSdn($sdn)
    {
        if (is_null($sdn)) {
            throw new \InvalidArgumentException('non-nullable sdn cannot be null');
        }
        $this->container['sdn'] = $sdn;

        return $this;
    }
    

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Resource type dependent status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    

    /**
     * Gets storage
     *
     * @return string|null
     */
    public function getStorage()
    {
        return $this->container['storage'];
    }

    /**
     * Sets storage
     *
     * @param string|null $storage The storage identifier (for type 'storage').
     *
     * @return self
     */
    public function setStorage($storage)
    {
        if (is_null($storage)) {
            throw new \InvalidArgumentException('non-nullable storage cannot be null');
        }

        if ((!preg_match("/^[a-z][a-z0-9\\-_.]*[a-z0-9]$/", ObjectSerializer::toString($storage)))) {
            throw new \InvalidArgumentException("invalid value for \$storage when calling ClusterResourcesResponseDataInner., must conform to the pattern /^[a-z][a-z0-9\\-_.]*[a-z0-9]$/.");
        }

        $this->container['storage'] = $storage;

        return $this;
    }
    

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags The guest's tags (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }
    

    /**
     * Gets template
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $template Determines if the guest is a template. (for types 'qemu' and 'lxc')
     *
     * @return self
     */
    public function setTemplate($template)
    {
        if (is_null($template)) {
            throw new \InvalidArgumentException('non-nullable template cannot be null');
        }
        $this->container['template'] = $template;

        return $this;
    }
    

    /**
     * Gets type
     *
     * @return \ClientApi\PveClient\Model\PveClusterTypeEnum2
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \ClientApi\PveClient\Model\PveClusterTypeEnum2 $type Resource type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }
    

    /**
     * Gets uptime
     *
     * @return int|null
     */
    public function getUptime()
    {
        return $this->container['uptime'];
    }

    /**
     * Sets uptime
     *
     * @param int|null $uptime Uptime of node or virtual guest in seconds (for types 'node', 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setUptime($uptime)
    {
        if (is_null($uptime)) {
            throw new \InvalidArgumentException('non-nullable uptime cannot be null');
        }
        $this->container['uptime'] = $uptime;

        return $this;
    }
    

    /**
     * Gets vmid
     *
     * @return int|null
     */
    public function getVmid()
    {
        return $this->container['vmid'];
    }

    /**
     * Sets vmid
     *
     * @param int|null $vmid The numerical vmid (for types 'qemu' and 'lxc').
     *
     * @return self
     */
    public function setVmid($vmid)
    {
        if (is_null($vmid)) {
            throw new \InvalidArgumentException('non-nullable vmid cannot be null');
        }

        if (($vmid > 999999999)) {
            throw new \InvalidArgumentException('invalid value for $vmid when calling ClusterResourcesResponseDataInner., must be smaller than or equal to 999999999.');
        }
        if (($vmid < 100)) {
            throw new \InvalidArgumentException('invalid value for $vmid when calling ClusterResourcesResponseDataInner., must be bigger than or equal to 100.');
        }

        $this->container['vmid'] = $vmid;

        return $this;
    }
    

    /**
     * Gets zone_type
     *
     * @return string|null
     */
    public function getZoneType()
    {
        return $this->container['zone_type'];
    }

    /**
     * Sets zone_type
     *
     * @param string|null $zone_type The type of an SDN zone (for type 'sdn').
     *
     * @return self
     */
    public function setZoneType($zone_type)
    {
        if (is_null($zone_type)) {
            throw new \InvalidArgumentException('non-nullable zone_type cannot be null');
        }
        $this->container['zone_type'] = $zone_type;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



