<?php
/**
 * ClusterBackupCreateJobRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * ClusterBackupCreateJobRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClusterBackupCreateJobRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClusterBackupCreateJobRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'all' => '\ClientApi\PveClient\Model\PveBoolean',
        'bwlimit' => 'int',
        'comment' => 'string',
        'compress' => '\ClientApi\PveClient\Model\PveCompressEnum',
        'dow' => 'string',
        'dumpdir' => 'string',
        'enabled' => '\ClientApi\PveClient\Model\PveBoolean',
        'exclude' => 'string',
        'exclude_path' => 'string[]',
        'fleecing' => 'string',
        'id' => 'string',
        'ionice' => 'int',
        'lockwait' => 'int',
        'mailnotification' => '\ClientApi\PveClient\Model\PveMailnotificationEnum',
        'mailto' => 'string',
        'maxfiles' => 'int',
        'mode' => '\ClientApi\PveClient\Model\PveClusterBackupModeEnum',
        'node' => 'string',
        'notes_template' => 'string',
        'notification_mode' => '\ClientApi\PveClient\Model\PveNotificationModeEnum',
        'pbs_change_detection_mode' => '\ClientApi\PveClient\Model\PvePbsChangeDetectionModeEnum',
        'performance' => 'string',
        'pigz' => 'int',
        'pool' => 'string',
        'protected' => '\ClientApi\PveClient\Model\PveBoolean',
        'prune_backups' => 'string',
        'quiet' => '\ClientApi\PveClient\Model\PveBoolean',
        'remove' => '\ClientApi\PveClient\Model\PveBoolean',
        'repeat_missed' => '\ClientApi\PveClient\Model\PveBoolean',
        'schedule' => 'string',
        'script' => 'string',
        'starttime' => 'string',
        'stdexcludes' => '\ClientApi\PveClient\Model\PveBoolean',
        'stop' => '\ClientApi\PveClient\Model\PveBoolean',
        'stopwait' => 'int',
        'storage' => 'string',
        'tmpdir' => 'string',
        'vmid' => 'string',
        'zstd' => 'int',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'all' => null,
        'bwlimit' => 'int64',
        'comment' => null,
        'compress' => null,
        'dow' => 'pve-day-of-week-list',
        'dumpdir' => null,
        'enabled' => null,
        'exclude' => 'pve-vmid-list',
        'exclude_path' => null,
        'fleecing' => 'backup-fleecing',
        'id' => 'pve-configid',
        'ionice' => null,
        'lockwait' => 'int64',
        'mailnotification' => null,
        'mailto' => 'email-or-username-list',
        'maxfiles' => 'int64',
        'mode' => null,
        'node' => 'pve-node',
        'notes_template' => null,
        'notification_mode' => null,
        'pbs_change_detection_mode' => null,
        'performance' => 'backup-performance',
        'pigz' => 'int64',
        'pool' => null,
        'protected' => null,
        'prune_backups' => 'prune-backups',
        'quiet' => null,
        'remove' => null,
        'repeat_missed' => null,
        'schedule' => 'pve-calendar-event',
        'script' => null,
        'starttime' => null,
        'stdexcludes' => null,
        'stop' => null,
        'stopwait' => 'int64',
        'storage' => 'pve-storage-id',
        'tmpdir' => null,
        'vmid' => 'pve-vmid-list',
        'zstd' => 'int64',
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'all' => false,
        'bwlimit' => false,
        'comment' => false,
        'compress' => false,
        'dow' => false,
        'dumpdir' => false,
        'enabled' => false,
        'exclude' => false,
        'exclude_path' => false,
        'fleecing' => false,
        'id' => false,
        'ionice' => false,
        'lockwait' => false,
        'mailnotification' => false,
        'mailto' => false,
        'maxfiles' => false,
        'mode' => false,
        'node' => false,
        'notes_template' => false,
        'notification_mode' => false,
        'pbs_change_detection_mode' => false,
        'performance' => false,
        'pigz' => false,
        'pool' => false,
        'protected' => false,
        'prune_backups' => false,
        'quiet' => false,
        'remove' => false,
        'repeat_missed' => false,
        'schedule' => false,
        'script' => false,
        'starttime' => false,
        'stdexcludes' => false,
        'stop' => false,
        'stopwait' => false,
        'storage' => false,
        'tmpdir' => false,
        'vmid' => false,
        'zstd' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'all' => 'all',
        'bwlimit' => 'bwlimit',
        'comment' => 'comment',
        'compress' => 'compress',
        'dow' => 'dow',
        'dumpdir' => 'dumpdir',
        'enabled' => 'enabled',
        'exclude' => 'exclude',
        'exclude_path' => 'exclude-path',
        'fleecing' => 'fleecing',
        'id' => 'id',
        'ionice' => 'ionice',
        'lockwait' => 'lockwait',
        'mailnotification' => 'mailnotification',
        'mailto' => 'mailto',
        'maxfiles' => 'maxfiles',
        'mode' => 'mode',
        'node' => 'node',
        'notes_template' => 'notes-template',
        'notification_mode' => 'notification-mode',
        'pbs_change_detection_mode' => 'pbs-change-detection-mode',
        'performance' => 'performance',
        'pigz' => 'pigz',
        'pool' => 'pool',
        'protected' => 'protected',
        'prune_backups' => 'prune-backups',
        'quiet' => 'quiet',
        'remove' => 'remove',
        'repeat_missed' => 'repeat-missed',
        'schedule' => 'schedule',
        'script' => 'script',
        'starttime' => 'starttime',
        'stdexcludes' => 'stdexcludes',
        'stop' => 'stop',
        'stopwait' => 'stopwait',
        'storage' => 'storage',
        'tmpdir' => 'tmpdir',
        'vmid' => 'vmid',
        'zstd' => 'zstd',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'all' => 'setAll',
        'bwlimit' => 'setBwlimit',
        'comment' => 'setComment',
        'compress' => 'setCompress',
        'dow' => 'setDow',
        'dumpdir' => 'setDumpdir',
        'enabled' => 'setEnabled',
        'exclude' => 'setExclude',
        'exclude_path' => 'setExcludePath',
        'fleecing' => 'setFleecing',
        'id' => 'setId',
        'ionice' => 'setIonice',
        'lockwait' => 'setLockwait',
        'mailnotification' => 'setMailnotification',
        'mailto' => 'setMailto',
        'maxfiles' => 'setMaxfiles',
        'mode' => 'setMode',
        'node' => 'setNode',
        'notes_template' => 'setNotesTemplate',
        'notification_mode' => 'setNotificationMode',
        'pbs_change_detection_mode' => 'setPbsChangeDetectionMode',
        'performance' => 'setPerformance',
        'pigz' => 'setPigz',
        'pool' => 'setPool',
        'protected' => 'setProtected',
        'prune_backups' => 'setPruneBackups',
        'quiet' => 'setQuiet',
        'remove' => 'setRemove',
        'repeat_missed' => 'setRepeatMissed',
        'schedule' => 'setSchedule',
        'script' => 'setScript',
        'starttime' => 'setStarttime',
        'stdexcludes' => 'setStdexcludes',
        'stop' => 'setStop',
        'stopwait' => 'setStopwait',
        'storage' => 'setStorage',
        'tmpdir' => 'setTmpdir',
        'vmid' => 'setVmid',
        'zstd' => 'setZstd',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'all' => 'getAll',
        'bwlimit' => 'getBwlimit',
        'comment' => 'getComment',
        'compress' => 'getCompress',
        'dow' => 'getDow',
        'dumpdir' => 'getDumpdir',
        'enabled' => 'getEnabled',
        'exclude' => 'getExclude',
        'exclude_path' => 'getExcludePath',
        'fleecing' => 'getFleecing',
        'id' => 'getId',
        'ionice' => 'getIonice',
        'lockwait' => 'getLockwait',
        'mailnotification' => 'getMailnotification',
        'mailto' => 'getMailto',
        'maxfiles' => 'getMaxfiles',
        'mode' => 'getMode',
        'node' => 'getNode',
        'notes_template' => 'getNotesTemplate',
        'notification_mode' => 'getNotificationMode',
        'pbs_change_detection_mode' => 'getPbsChangeDetectionMode',
        'performance' => 'getPerformance',
        'pigz' => 'getPigz',
        'pool' => 'getPool',
        'protected' => 'getProtected',
        'prune_backups' => 'getPruneBackups',
        'quiet' => 'getQuiet',
        'remove' => 'getRemove',
        'repeat_missed' => 'getRepeatMissed',
        'schedule' => 'getSchedule',
        'script' => 'getScript',
        'starttime' => 'getStarttime',
        'stdexcludes' => 'getStdexcludes',
        'stop' => 'getStop',
        'stopwait' => 'getStopwait',
        'storage' => 'getStorage',
        'tmpdir' => 'getTmpdir',
        'vmid' => 'getVmid',
        'zstd' => 'getZstd',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('all', $data ?? [], 0);
        
        $this->setIfExists('bwlimit', $data ?? [], 0);
        
        $this->setIfExists('comment', $data ?? [], null);
        
        $this->setIfExists('compress', $data ?? [], PveCompressEnum::_0);
        
        $this->setIfExists('dow', $data ?? [], 'mon,tue,wed,thu,fri,sat,sun');
        
        $this->setIfExists('dumpdir', $data ?? [], null);
        
        $this->setIfExists('enabled', $data ?? [], 1);
        
        $this->setIfExists('exclude', $data ?? [], null);
        
        $this->setIfExists('exclude_path', $data ?? [], null);
        
        $this->setIfExists('fleecing', $data ?? [], null);
        
        $this->setIfExists('id', $data ?? [], null);
        
        $this->setIfExists('ionice', $data ?? [], 7);
        
        $this->setIfExists('lockwait', $data ?? [], 180);
        
        $this->setIfExists('mailnotification', $data ?? [], PveMailnotificationEnum::ALWAYS);
        
        $this->setIfExists('mailto', $data ?? [], null);
        
        $this->setIfExists('maxfiles', $data ?? [], null);
        
        $this->setIfExists('mode', $data ?? [], PveClusterBackupModeEnum::SNAPSHOT);
        
        $this->setIfExists('node', $data ?? [], null);
        
        $this->setIfExists('notes_template', $data ?? [], null);
        
        $this->setIfExists('notification_mode', $data ?? [], PveNotificationModeEnum::AUTO);
        
        $this->setIfExists('pbs_change_detection_mode', $data ?? [], null);
        
        $this->setIfExists('performance', $data ?? [], null);
        
        $this->setIfExists('pigz', $data ?? [], 0);
        
        $this->setIfExists('pool', $data ?? [], null);
        
        $this->setIfExists('protected', $data ?? [], null);
        
        $this->setIfExists('prune_backups', $data ?? [], 'keep-all=1');
        
        $this->setIfExists('quiet', $data ?? [], 0);
        
        $this->setIfExists('remove', $data ?? [], 1);
        
        $this->setIfExists('repeat_missed', $data ?? [], 0);
        
        $this->setIfExists('schedule', $data ?? [], null);
        
        $this->setIfExists('script', $data ?? [], null);
        
        $this->setIfExists('starttime', $data ?? [], null);
        
        $this->setIfExists('stdexcludes', $data ?? [], 1);
        
        $this->setIfExists('stop', $data ?? [], 0);
        
        $this->setIfExists('stopwait', $data ?? [], 10);
        
        $this->setIfExists('storage', $data ?? [], null);
        
        $this->setIfExists('tmpdir', $data ?? [], null);
        
        $this->setIfExists('vmid', $data ?? [], null);
        
        $this->setIfExists('zstd', $data ?? [], 1);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        if (!is_null($this->container['bwlimit']) && ($this->container['bwlimit'] < 0)) {
            $invalidProperties[] = "invalid value for 'bwlimit', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['comment']) && (mb_strlen($this->container['comment']) > 512)) {
            $invalidProperties[] = "invalid value for 'comment', the character length must be smaller than or equal to 512.";
        }

        
        
        if (!is_null($this->container['dow']) && !preg_match("/^(?:mon|tue|wed|thu|fri|sat|sun)(?:,(?:mon|tue|wed|thu|fri|sat|sun))*$/", $this->container['dow'])) {
            $invalidProperties[] = "invalid value for 'dow', must be conform to the pattern /^(?:mon|tue|wed|thu|fri|sat|sun)(?:,(?:mon|tue|wed|thu|fri|sat|sun))*$/.";
        }

        
        
        
        
        
        
        if (!is_null($this->container['id']) && !preg_match("/^[A-Za-z][A-Za-z0-9_]*$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[A-Za-z][A-Za-z0-9_]*$/.";
        }

        
        if (!is_null($this->container['ionice']) && ($this->container['ionice'] > 8)) {
            $invalidProperties[] = "invalid value for 'ionice', must be smaller than or equal to 8.";
        }

        if (!is_null($this->container['ionice']) && ($this->container['ionice'] < 0)) {
            $invalidProperties[] = "invalid value for 'ionice', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['lockwait']) && ($this->container['lockwait'] < 0)) {
            $invalidProperties[] = "invalid value for 'lockwait', must be bigger than or equal to 0.";
        }

        
        
        
        if (!is_null($this->container['maxfiles']) && ($this->container['maxfiles'] < 1)) {
            $invalidProperties[] = "invalid value for 'maxfiles', must be bigger than or equal to 1.";
        }

        
        
        if (!is_null($this->container['node']) && !preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $this->container['node'])) {
            $invalidProperties[] = "invalid value for 'node', must be conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.";
        }

        
        if (!is_null($this->container['notes_template']) && (mb_strlen($this->container['notes_template']) > 1024)) {
            $invalidProperties[] = "invalid value for 'notes_template', the character length must be smaller than or equal to 1024.";
        }

        
        
        
        
        
        
        
        
        
        
        
        if (!is_null($this->container['schedule']) && (mb_strlen($this->container['schedule']) > 128)) {
            $invalidProperties[] = "invalid value for 'schedule', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['schedule']) && !preg_match("/.+/", $this->container['schedule'])) {
            $invalidProperties[] = "invalid value for 'schedule', must be conform to the pattern /.+/.";
        }

        
        
        if (!is_null($this->container['starttime']) && !preg_match("/\\d{1,2}:\\d{1,2}/", $this->container['starttime'])) {
            $invalidProperties[] = "invalid value for 'starttime', must be conform to the pattern /\\d{1,2}:\\d{1,2}/.";
        }

        
        
        
        if (!is_null($this->container['stopwait']) && ($this->container['stopwait'] < 0)) {
            $invalidProperties[] = "invalid value for 'stopwait', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['storage']) && !preg_match("/^[a-z][a-z0-9\\-_.]*[a-z0-9]$/", $this->container['storage'])) {
            $invalidProperties[] = "invalid value for 'storage', must be conform to the pattern /^[a-z][a-z0-9\\-_.]*[a-z0-9]$/.";
        }

        
        
        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets all
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getAll()
    {
        return $this->container['all'];
    }

    /**
     * Sets all
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $all Backup all known guest systems on this host.
     *
     * @return self
     */
    public function setAll($all)
    {
        if (is_null($all)) {
            throw new \InvalidArgumentException('non-nullable all cannot be null');
        }
        $this->container['all'] = $all;

        return $this;
    }
    

    /**
     * Gets bwlimit
     *
     * @return int|null
     */
    public function getBwlimit()
    {
        return $this->container['bwlimit'];
    }

    /**
     * Sets bwlimit
     *
     * @param int|null $bwlimit Limit I/O bandwidth (in KiB/s).
     *
     * @return self
     */
    public function setBwlimit($bwlimit)
    {
        if (is_null($bwlimit)) {
            throw new \InvalidArgumentException('non-nullable bwlimit cannot be null');
        }

        if (($bwlimit < 0)) {
            throw new \InvalidArgumentException('invalid value for $bwlimit when calling ClusterBackupCreateJobRequest., must be bigger than or equal to 0.');
        }

        $this->container['bwlimit'] = $bwlimit;

        return $this;
    }
    

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Description for the Job.
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        if ((mb_strlen($comment) > 512)) {
            throw new \InvalidArgumentException('invalid length for $comment when calling ClusterBackupCreateJobRequest., must be smaller than or equal to 512.');
        }

        $this->container['comment'] = $comment;

        return $this;
    }
    

    /**
     * Gets compress
     *
     * @return \ClientApi\PveClient\Model\PveCompressEnum|null
     */
    public function getCompress()
    {
        return $this->container['compress'];
    }

    /**
     * Sets compress
     *
     * @param \ClientApi\PveClient\Model\PveCompressEnum|null $compress Compress dump file.
     *
     * @return self
     */
    public function setCompress($compress)
    {
        if (is_null($compress)) {
            throw new \InvalidArgumentException('non-nullable compress cannot be null');
        }
        $this->container['compress'] = $compress;

        return $this;
    }
    

    /**
     * Gets dow
     *
     * @return string|null
     */
    public function getDow()
    {
        return $this->container['dow'];
    }

    /**
     * Sets dow
     *
     * @param string|null $dow Day of week selection.
     *
     * @return self
     */
    public function setDow($dow)
    {
        if (is_null($dow)) {
            throw new \InvalidArgumentException('non-nullable dow cannot be null');
        }

        if ((!preg_match("/^(?:mon|tue|wed|thu|fri|sat|sun)(?:,(?:mon|tue|wed|thu|fri|sat|sun))*$/", ObjectSerializer::toString($dow)))) {
            throw new \InvalidArgumentException("invalid value for \$dow when calling ClusterBackupCreateJobRequest., must conform to the pattern /^(?:mon|tue|wed|thu|fri|sat|sun)(?:,(?:mon|tue|wed|thu|fri|sat|sun))*$/.");
        }

        $this->container['dow'] = $dow;

        return $this;
    }
    

    /**
     * Gets dumpdir
     *
     * @return string|null
     */
    public function getDumpdir()
    {
        return $this->container['dumpdir'];
    }

    /**
     * Sets dumpdir
     *
     * @param string|null $dumpdir Store resulting files to specified directory.
     *
     * @return self
     */
    public function setDumpdir($dumpdir)
    {
        if (is_null($dumpdir)) {
            throw new \InvalidArgumentException('non-nullable dumpdir cannot be null');
        }
        $this->container['dumpdir'] = $dumpdir;

        return $this;
    }
    

    /**
     * Gets enabled
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $enabled Enable or disable the job.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }
    

    /**
     * Gets exclude
     *
     * @return string|null
     */
    public function getExclude()
    {
        return $this->container['exclude'];
    }

    /**
     * Sets exclude
     *
     * @param string|null $exclude Exclude specified guest systems (assumes --all)
     *
     * @return self
     */
    public function setExclude($exclude)
    {
        if (is_null($exclude)) {
            throw new \InvalidArgumentException('non-nullable exclude cannot be null');
        }
        $this->container['exclude'] = $exclude;

        return $this;
    }
    

    /**
     * Gets exclude_path
     *
     * @return string[]|null
     */
    public function getExcludePath()
    {
        return $this->container['exclude_path'];
    }

    /**
     * Sets exclude_path
     *
     * @param string[]|null $exclude_path Exclude certain files/directories (shell globs). Paths starting with '/' are anchored to the container's root, other paths match relative to each subdirectory.
     *
     * @return self
     */
    public function setExcludePath($exclude_path)
    {
        if (is_null($exclude_path)) {
            throw new \InvalidArgumentException('non-nullable exclude_path cannot be null');
        }
        $this->container['exclude_path'] = $exclude_path;

        return $this;
    }
    

    /**
     * Gets fleecing
     *
     * @return string|null
     */
    public function getFleecing()
    {
        return $this->container['fleecing'];
    }

    /**
     * Sets fleecing
     *
     * @param string|null $fleecing Options for backup fleecing (VM only).
     *
     * @return self
     */
    public function setFleecing($fleecing)
    {
        if (is_null($fleecing)) {
            throw new \InvalidArgumentException('non-nullable fleecing cannot be null');
        }
        $this->container['fleecing'] = $fleecing;

        return $this;
    }
    

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Job ID (will be autogenerated).
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if ((!preg_match("/^[A-Za-z][A-Za-z0-9_]*$/", ObjectSerializer::toString($id)))) {
            throw new \InvalidArgumentException("invalid value for \$id when calling ClusterBackupCreateJobRequest., must conform to the pattern /^[A-Za-z][A-Za-z0-9_]*$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }
    

    /**
     * Gets ionice
     *
     * @return int|null
     */
    public function getIonice()
    {
        return $this->container['ionice'];
    }

    /**
     * Sets ionice
     *
     * @param int|null $ionice Set IO priority when using the BFQ scheduler. For snapshot and suspend mode backups of VMs, this only affects the compressor. A value of 8 means the idle priority is used, otherwise the best-effort priority is used with the specified value.
     *
     * @return self
     */
    public function setIonice($ionice)
    {
        if (is_null($ionice)) {
            throw new \InvalidArgumentException('non-nullable ionice cannot be null');
        }

        if (($ionice > 8)) {
            throw new \InvalidArgumentException('invalid value for $ionice when calling ClusterBackupCreateJobRequest., must be smaller than or equal to 8.');
        }
        if (($ionice < 0)) {
            throw new \InvalidArgumentException('invalid value for $ionice when calling ClusterBackupCreateJobRequest., must be bigger than or equal to 0.');
        }

        $this->container['ionice'] = $ionice;

        return $this;
    }
    

    /**
     * Gets lockwait
     *
     * @return int|null
     */
    public function getLockwait()
    {
        return $this->container['lockwait'];
    }

    /**
     * Sets lockwait
     *
     * @param int|null $lockwait Maximal time to wait for the global lock (minutes).
     *
     * @return self
     */
    public function setLockwait($lockwait)
    {
        if (is_null($lockwait)) {
            throw new \InvalidArgumentException('non-nullable lockwait cannot be null');
        }

        if (($lockwait < 0)) {
            throw new \InvalidArgumentException('invalid value for $lockwait when calling ClusterBackupCreateJobRequest., must be bigger than or equal to 0.');
        }

        $this->container['lockwait'] = $lockwait;

        return $this;
    }
    

    /**
     * Gets mailnotification
     *
     * @return \ClientApi\PveClient\Model\PveMailnotificationEnum|null
     */
    public function getMailnotification()
    {
        return $this->container['mailnotification'];
    }

    /**
     * Sets mailnotification
     *
     * @param \ClientApi\PveClient\Model\PveMailnotificationEnum|null $mailnotification Deprecated: use notification targets/matchers instead. Specify when to send a notification mail
     *
     * @return self
     */
    public function setMailnotification($mailnotification)
    {
        if (is_null($mailnotification)) {
            throw new \InvalidArgumentException('non-nullable mailnotification cannot be null');
        }
        $this->container['mailnotification'] = $mailnotification;

        return $this;
    }
    

    /**
     * Gets mailto
     *
     * @return string|null
     */
    public function getMailto()
    {
        return $this->container['mailto'];
    }

    /**
     * Sets mailto
     *
     * @param string|null $mailto Deprecated: Use notification targets/matchers instead. Comma-separated list of email addresses or users that should receive email notifications.
     *
     * @return self
     */
    public function setMailto($mailto)
    {
        if (is_null($mailto)) {
            throw new \InvalidArgumentException('non-nullable mailto cannot be null');
        }
        $this->container['mailto'] = $mailto;

        return $this;
    }
    

    /**
     * Gets maxfiles
     *
     * @return int|null
     */
    public function getMaxfiles()
    {
        return $this->container['maxfiles'];
    }

    /**
     * Sets maxfiles
     *
     * @param int|null $maxfiles Deprecated: use 'prune-backups' instead. Maximal number of backup files per guest system.
     *
     * @return self
     */
    public function setMaxfiles($maxfiles)
    {
        if (is_null($maxfiles)) {
            throw new \InvalidArgumentException('non-nullable maxfiles cannot be null');
        }

        if (($maxfiles < 1)) {
            throw new \InvalidArgumentException('invalid value for $maxfiles when calling ClusterBackupCreateJobRequest., must be bigger than or equal to 1.');
        }

        $this->container['maxfiles'] = $maxfiles;

        return $this;
    }
    

    /**
     * Gets mode
     *
     * @return \ClientApi\PveClient\Model\PveClusterBackupModeEnum|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param \ClientApi\PveClient\Model\PveClusterBackupModeEnum|null $mode Backup mode.
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }
    

    /**
     * Gets node
     *
     * @return string|null
     */
    public function getNode()
    {
        return $this->container['node'];
    }

    /**
     * Sets node
     *
     * @param string|null $node Only run if executed on this node.
     *
     * @return self
     */
    public function setNode($node)
    {
        if (is_null($node)) {
            throw new \InvalidArgumentException('non-nullable node cannot be null');
        }

        if ((!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", ObjectSerializer::toString($node)))) {
            throw new \InvalidArgumentException("invalid value for \$node when calling ClusterBackupCreateJobRequest., must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }

        $this->container['node'] = $node;

        return $this;
    }
    

    /**
     * Gets notes_template
     *
     * @return string|null
     */
    public function getNotesTemplate()
    {
        return $this->container['notes_template'];
    }

    /**
     * Sets notes_template
     *
     * @param string|null $notes_template Template string for generating notes for the backup(s). It can contain variables which will be replaced by their values. Currently supported are {{cluster}}, {{guestname}}, {{node}}, and {{vmid}}, but more might be added in the future. Needs to be a single line, newline and backslash need to be escaped as '\\n' and '\\\\' respectively.
     *
     * @return self
     */
    public function setNotesTemplate($notes_template)
    {
        if (is_null($notes_template)) {
            throw new \InvalidArgumentException('non-nullable notes_template cannot be null');
        }
        if ((mb_strlen($notes_template) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $notes_template when calling ClusterBackupCreateJobRequest., must be smaller than or equal to 1024.');
        }

        $this->container['notes_template'] = $notes_template;

        return $this;
    }
    

    /**
     * Gets notification_mode
     *
     * @return \ClientApi\PveClient\Model\PveNotificationModeEnum|null
     */
    public function getNotificationMode()
    {
        return $this->container['notification_mode'];
    }

    /**
     * Sets notification_mode
     *
     * @param \ClientApi\PveClient\Model\PveNotificationModeEnum|null $notification_mode Determine which notification system to use. If set to 'legacy-sendmail', vzdump will consider the mailto/mailnotification parameters and send emails to the specified address(es) via the 'sendmail' command. If set to 'notification-system', a notification will be sent via PVE's notification system, and the mailto and mailnotification will be ignored. If set to 'auto' (default setting), an email will be sent if mailto is set, and the notification system will be used if not.
     *
     * @return self
     */
    public function setNotificationMode($notification_mode)
    {
        if (is_null($notification_mode)) {
            throw new \InvalidArgumentException('non-nullable notification_mode cannot be null');
        }
        $this->container['notification_mode'] = $notification_mode;

        return $this;
    }
    

    /**
     * Gets pbs_change_detection_mode
     *
     * @return \ClientApi\PveClient\Model\PvePbsChangeDetectionModeEnum|null
     */
    public function getPbsChangeDetectionMode()
    {
        return $this->container['pbs_change_detection_mode'];
    }

    /**
     * Sets pbs_change_detection_mode
     *
     * @param \ClientApi\PveClient\Model\PvePbsChangeDetectionModeEnum|null $pbs_change_detection_mode PBS mode used to detect file changes and switch encoding format for container backups.
     *
     * @return self
     */
    public function setPbsChangeDetectionMode($pbs_change_detection_mode)
    {
        if (is_null($pbs_change_detection_mode)) {
            throw new \InvalidArgumentException('non-nullable pbs_change_detection_mode cannot be null');
        }
        $this->container['pbs_change_detection_mode'] = $pbs_change_detection_mode;

        return $this;
    }
    

    /**
     * Gets performance
     *
     * @return string|null
     */
    public function getPerformance()
    {
        return $this->container['performance'];
    }

    /**
     * Sets performance
     *
     * @param string|null $performance Other performance-related settings.
     *
     * @return self
     */
    public function setPerformance($performance)
    {
        if (is_null($performance)) {
            throw new \InvalidArgumentException('non-nullable performance cannot be null');
        }
        $this->container['performance'] = $performance;

        return $this;
    }
    

    /**
     * Gets pigz
     *
     * @return int|null
     */
    public function getPigz()
    {
        return $this->container['pigz'];
    }

    /**
     * Sets pigz
     *
     * @param int|null $pigz Use pigz instead of gzip when N>0. N=1 uses half of cores, N>1 uses N as thread count.
     *
     * @return self
     */
    public function setPigz($pigz)
    {
        if (is_null($pigz)) {
            throw new \InvalidArgumentException('non-nullable pigz cannot be null');
        }
        $this->container['pigz'] = $pigz;

        return $this;
    }
    

    /**
     * Gets pool
     *
     * @return string|null
     */
    public function getPool()
    {
        return $this->container['pool'];
    }

    /**
     * Sets pool
     *
     * @param string|null $pool Backup all known guest systems included in the specified pool.
     *
     * @return self
     */
    public function setPool($pool)
    {
        if (is_null($pool)) {
            throw new \InvalidArgumentException('non-nullable pool cannot be null');
        }
        $this->container['pool'] = $pool;

        return $this;
    }
    

    /**
     * Gets protected
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getProtected()
    {
        return $this->container['protected'];
    }

    /**
     * Sets protected
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $protected If true, mark backup(s) as protected.
     *
     * @return self
     */
    public function setProtected($protected)
    {
        if (is_null($protected)) {
            throw new \InvalidArgumentException('non-nullable protected cannot be null');
        }
        $this->container['protected'] = $protected;

        return $this;
    }
    

    /**
     * Gets prune_backups
     *
     * @return string|null
     */
    public function getPruneBackups()
    {
        return $this->container['prune_backups'];
    }

    /**
     * Sets prune_backups
     *
     * @param string|null $prune_backups Use these retention options instead of those from the storage configuration.
     *
     * @return self
     */
    public function setPruneBackups($prune_backups)
    {
        if (is_null($prune_backups)) {
            throw new \InvalidArgumentException('non-nullable prune_backups cannot be null');
        }
        $this->container['prune_backups'] = $prune_backups;

        return $this;
    }
    

    /**
     * Gets quiet
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getQuiet()
    {
        return $this->container['quiet'];
    }

    /**
     * Sets quiet
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $quiet Be quiet.
     *
     * @return self
     */
    public function setQuiet($quiet)
    {
        if (is_null($quiet)) {
            throw new \InvalidArgumentException('non-nullable quiet cannot be null');
        }
        $this->container['quiet'] = $quiet;

        return $this;
    }
    

    /**
     * Gets remove
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getRemove()
    {
        return $this->container['remove'];
    }

    /**
     * Sets remove
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $remove Prune older backups according to 'prune-backups'.
     *
     * @return self
     */
    public function setRemove($remove)
    {
        if (is_null($remove)) {
            throw new \InvalidArgumentException('non-nullable remove cannot be null');
        }
        $this->container['remove'] = $remove;

        return $this;
    }
    

    /**
     * Gets repeat_missed
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getRepeatMissed()
    {
        return $this->container['repeat_missed'];
    }

    /**
     * Sets repeat_missed
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $repeat_missed If true, the job will be run as soon as possible if it was missed while the scheduler was not running.
     *
     * @return self
     */
    public function setRepeatMissed($repeat_missed)
    {
        if (is_null($repeat_missed)) {
            throw new \InvalidArgumentException('non-nullable repeat_missed cannot be null');
        }
        $this->container['repeat_missed'] = $repeat_missed;

        return $this;
    }
    

    /**
     * Gets schedule
     *
     * @return string|null
     */
    public function getSchedule()
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param string|null $schedule Backup schedule. The format is a subset of `systemd` calendar events.
     *
     * @return self
     */
    public function setSchedule($schedule)
    {
        if (is_null($schedule)) {
            throw new \InvalidArgumentException('non-nullable schedule cannot be null');
        }
        if ((mb_strlen($schedule) > 128)) {
            throw new \InvalidArgumentException('invalid length for $schedule when calling ClusterBackupCreateJobRequest., must be smaller than or equal to 128.');
        }
        if ((!preg_match("/.+/", ObjectSerializer::toString($schedule)))) {
            throw new \InvalidArgumentException("invalid value for \$schedule when calling ClusterBackupCreateJobRequest., must conform to the pattern /.+/.");
        }

        $this->container['schedule'] = $schedule;

        return $this;
    }
    

    /**
     * Gets script
     *
     * @return string|null
     */
    public function getScript()
    {
        return $this->container['script'];
    }

    /**
     * Sets script
     *
     * @param string|null $script Use specified hook script.
     *
     * @return self
     */
    public function setScript($script)
    {
        if (is_null($script)) {
            throw new \InvalidArgumentException('non-nullable script cannot be null');
        }
        $this->container['script'] = $script;

        return $this;
    }
    

    /**
     * Gets starttime
     *
     * @return string|null
     */
    public function getStarttime()
    {
        return $this->container['starttime'];
    }

    /**
     * Sets starttime
     *
     * @param string|null $starttime Job Start time.
     *
     * @return self
     */
    public function setStarttime($starttime)
    {
        if (is_null($starttime)) {
            throw new \InvalidArgumentException('non-nullable starttime cannot be null');
        }

        if ((!preg_match("/\\d{1,2}:\\d{1,2}/", ObjectSerializer::toString($starttime)))) {
            throw new \InvalidArgumentException("invalid value for \$starttime when calling ClusterBackupCreateJobRequest., must conform to the pattern /\\d{1,2}:\\d{1,2}/.");
        }

        $this->container['starttime'] = $starttime;

        return $this;
    }
    

    /**
     * Gets stdexcludes
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getStdexcludes()
    {
        return $this->container['stdexcludes'];
    }

    /**
     * Sets stdexcludes
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $stdexcludes Exclude temporary files and logs.
     *
     * @return self
     */
    public function setStdexcludes($stdexcludes)
    {
        if (is_null($stdexcludes)) {
            throw new \InvalidArgumentException('non-nullable stdexcludes cannot be null');
        }
        $this->container['stdexcludes'] = $stdexcludes;

        return $this;
    }
    

    /**
     * Gets stop
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getStop()
    {
        return $this->container['stop'];
    }

    /**
     * Sets stop
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $stop Stop running backup jobs on this host.
     *
     * @return self
     */
    public function setStop($stop)
    {
        if (is_null($stop)) {
            throw new \InvalidArgumentException('non-nullable stop cannot be null');
        }
        $this->container['stop'] = $stop;

        return $this;
    }
    

    /**
     * Gets stopwait
     *
     * @return int|null
     */
    public function getStopwait()
    {
        return $this->container['stopwait'];
    }

    /**
     * Sets stopwait
     *
     * @param int|null $stopwait Maximal time to wait until a guest system is stopped (minutes).
     *
     * @return self
     */
    public function setStopwait($stopwait)
    {
        if (is_null($stopwait)) {
            throw new \InvalidArgumentException('non-nullable stopwait cannot be null');
        }

        if (($stopwait < 0)) {
            throw new \InvalidArgumentException('invalid value for $stopwait when calling ClusterBackupCreateJobRequest., must be bigger than or equal to 0.');
        }

        $this->container['stopwait'] = $stopwait;

        return $this;
    }
    

    /**
     * Gets storage
     *
     * @return string|null
     */
    public function getStorage()
    {
        return $this->container['storage'];
    }

    /**
     * Sets storage
     *
     * @param string|null $storage Store resulting file to this storage.
     *
     * @return self
     */
    public function setStorage($storage)
    {
        if (is_null($storage)) {
            throw new \InvalidArgumentException('non-nullable storage cannot be null');
        }

        if ((!preg_match("/^[a-z][a-z0-9\\-_.]*[a-z0-9]$/", ObjectSerializer::toString($storage)))) {
            throw new \InvalidArgumentException("invalid value for \$storage when calling ClusterBackupCreateJobRequest., must conform to the pattern /^[a-z][a-z0-9\\-_.]*[a-z0-9]$/.");
        }

        $this->container['storage'] = $storage;

        return $this;
    }
    

    /**
     * Gets tmpdir
     *
     * @return string|null
     */
    public function getTmpdir()
    {
        return $this->container['tmpdir'];
    }

    /**
     * Sets tmpdir
     *
     * @param string|null $tmpdir Store temporary files to specified directory.
     *
     * @return self
     */
    public function setTmpdir($tmpdir)
    {
        if (is_null($tmpdir)) {
            throw new \InvalidArgumentException('non-nullable tmpdir cannot be null');
        }
        $this->container['tmpdir'] = $tmpdir;

        return $this;
    }
    

    /**
     * Gets vmid
     *
     * @return string|null
     */
    public function getVmid()
    {
        return $this->container['vmid'];
    }

    /**
     * Sets vmid
     *
     * @param string|null $vmid The ID of the guest system you want to backup.
     *
     * @return self
     */
    public function setVmid($vmid)
    {
        if (is_null($vmid)) {
            throw new \InvalidArgumentException('non-nullable vmid cannot be null');
        }
        $this->container['vmid'] = $vmid;

        return $this;
    }
    

    /**
     * Gets zstd
     *
     * @return int|null
     */
    public function getZstd()
    {
        return $this->container['zstd'];
    }

    /**
     * Sets zstd
     *
     * @param int|null $zstd Zstd threads. N=0 uses half of the available cores, if N is set to a value bigger than 0, N is used as thread count.
     *
     * @return self
     */
    public function setZstd($zstd)
    {
        if (is_null($zstd)) {
            throw new \InvalidArgumentException('non-nullable zstd cannot be null');
        }
        $this->container['zstd'] = $zstd;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



