<?php
/**
 * ClusterAcmeRegisterAccountRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * ClusterAcmeRegisterAccountRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClusterAcmeRegisterAccountRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClusterAcmeRegisterAccountRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'contact' => 'string',
        'directory' => 'string',
        'eab_hmac_key' => 'string',
        'eab_kid' => 'string',
        'name' => 'string',
        'tos_url' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'contact' => 'email-list',
        'directory' => null,
        'eab_hmac_key' => null,
        'eab_kid' => null,
        'name' => 'pve-configid',
        'tos_url' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'contact' => false,
        'directory' => false,
        'eab_hmac_key' => false,
        'eab_kid' => false,
        'name' => false,
        'tos_url' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contact' => 'contact',
        'directory' => 'directory',
        'eab_hmac_key' => 'eab-hmac-key',
        'eab_kid' => 'eab-kid',
        'name' => 'name',
        'tos_url' => 'tos_url',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contact' => 'setContact',
        'directory' => 'setDirectory',
        'eab_hmac_key' => 'setEabHmacKey',
        'eab_kid' => 'setEabKid',
        'name' => 'setName',
        'tos_url' => 'setTosUrl',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contact' => 'getContact',
        'directory' => 'getDirectory',
        'eab_hmac_key' => 'getEabHmacKey',
        'eab_kid' => 'getEabKid',
        'name' => 'getName',
        'tos_url' => 'getTosUrl',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('contact', $data ?? [], null);
        
        $this->setIfExists('directory', $data ?? [], 'https://acme-v02.api.letsencrypt.org/directory');
        
        $this->setIfExists('eab_hmac_key', $data ?? [], null);
        
        $this->setIfExists('eab_kid', $data ?? [], null);
        
        $this->setIfExists('name', $data ?? [], 'default');
        
        $this->setIfExists('tos_url', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if ($this->container['contact'] === null) {
            $invalidProperties[] = "'contact' can't be null";
        }
        
        if (!is_null($this->container['directory']) && !preg_match("/^https?:\/\/.*/", $this->container['directory'])) {
            $invalidProperties[] = "invalid value for 'directory', must be conform to the pattern /^https?:\/\/.*/.";
        }

        
        
        
        if (!is_null($this->container['name']) && !preg_match("/^[A-Za-z][A-Za-z0-9_]*$/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /^[A-Za-z][A-Za-z0-9_]*$/.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets contact
     *
     * @return string
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param string $contact Contact email addresses.
     *
     * @return self
     */
    public function setContact($contact)
    {
        if (is_null($contact)) {
            throw new \InvalidArgumentException('non-nullable contact cannot be null');
        }
        $this->container['contact'] = $contact;

        return $this;
    }
    

    /**
     * Gets directory
     *
     * @return string|null
     */
    public function getDirectory()
    {
        return $this->container['directory'];
    }

    /**
     * Sets directory
     *
     * @param string|null $directory URL of ACME CA directory endpoint.
     *
     * @return self
     */
    public function setDirectory($directory)
    {
        if (is_null($directory)) {
            throw new \InvalidArgumentException('non-nullable directory cannot be null');
        }

        if ((!preg_match("/^https?:\/\/.*/", ObjectSerializer::toString($directory)))) {
            throw new \InvalidArgumentException("invalid value for \$directory when calling ClusterAcmeRegisterAccountRequest., must conform to the pattern /^https?:\/\/.*/.");
        }

        $this->container['directory'] = $directory;

        return $this;
    }
    

    /**
     * Gets eab_hmac_key
     *
     * @return string|null
     */
    public function getEabHmacKey()
    {
        return $this->container['eab_hmac_key'];
    }

    /**
     * Sets eab_hmac_key
     *
     * @param string|null $eab_hmac_key HMAC key for External Account Binding.
     *
     * @return self
     */
    public function setEabHmacKey($eab_hmac_key)
    {
        if (is_null($eab_hmac_key)) {
            throw new \InvalidArgumentException('non-nullable eab_hmac_key cannot be null');
        }
        $this->container['eab_hmac_key'] = $eab_hmac_key;

        return $this;
    }
    

    /**
     * Gets eab_kid
     *
     * @return string|null
     */
    public function getEabKid()
    {
        return $this->container['eab_kid'];
    }

    /**
     * Sets eab_kid
     *
     * @param string|null $eab_kid Key Identifier for External Account Binding.
     *
     * @return self
     */
    public function setEabKid($eab_kid)
    {
        if (is_null($eab_kid)) {
            throw new \InvalidArgumentException('non-nullable eab_kid cannot be null');
        }
        $this->container['eab_kid'] = $eab_kid;

        return $this;
    }
    

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name ACME account config file name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((!preg_match("/^[A-Za-z][A-Za-z0-9_]*$/", ObjectSerializer::toString($name)))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling ClusterAcmeRegisterAccountRequest., must conform to the pattern /^[A-Za-z][A-Za-z0-9_]*$/.");
        }

        $this->container['name'] = $name;

        return $this;
    }
    

    /**
     * Gets tos_url
     *
     * @return string|null
     */
    public function getTosUrl()
    {
        return $this->container['tos_url'];
    }

    /**
     * Sets tos_url
     *
     * @param string|null $tos_url URL of CA TermsOfService - setting this indicates agreement.
     *
     * @return self
     */
    public function setTosUrl($tos_url)
    {
        if (is_null($tos_url)) {
            throw new \InvalidArgumentException('non-nullable tos_url cannot be null');
        }
        $this->container['tos_url'] = $tos_url;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



