<?php
/**
 * LxcSetOptionsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * LxcSetOptionsRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LxcSetOptionsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LxcSetOptionsRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'delete' => 'string',
        'dhcp' => '\ClientApi\PveClient\Model\PveBoolean',
        'digest' => 'string',
        'enable' => '\ClientApi\PveClient\Model\PveBoolean',
        'ipfilter' => '\ClientApi\PveClient\Model\PveBoolean',
        'log_level_in' => '\ClientApi\PveClient\Model\PveLogEnum',
        'log_level_out' => '\ClientApi\PveClient\Model\PveLogEnum',
        'macfilter' => '\ClientApi\PveClient\Model\PveBoolean',
        'ndp' => '\ClientApi\PveClient\Model\PveBoolean',
        'policy_in' => '\ClientApi\PveClient\Model\PvePolicyInEnum',
        'policy_out' => '\ClientApi\PveClient\Model\PvePolicyInEnum',
        'radv' => '\ClientApi\PveClient\Model\PveBoolean',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'delete' => 'pve-configid-list',
        'dhcp' => null,
        'digest' => null,
        'enable' => null,
        'ipfilter' => null,
        'log_level_in' => null,
        'log_level_out' => null,
        'macfilter' => null,
        'ndp' => null,
        'policy_in' => null,
        'policy_out' => null,
        'radv' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'delete' => false,
        'dhcp' => false,
        'digest' => false,
        'enable' => false,
        'ipfilter' => false,
        'log_level_in' => false,
        'log_level_out' => false,
        'macfilter' => false,
        'ndp' => false,
        'policy_in' => false,
        'policy_out' => false,
        'radv' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delete' => 'delete',
        'dhcp' => 'dhcp',
        'digest' => 'digest',
        'enable' => 'enable',
        'ipfilter' => 'ipfilter',
        'log_level_in' => 'log_level_in',
        'log_level_out' => 'log_level_out',
        'macfilter' => 'macfilter',
        'ndp' => 'ndp',
        'policy_in' => 'policy_in',
        'policy_out' => 'policy_out',
        'radv' => 'radv',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delete' => 'setDelete',
        'dhcp' => 'setDhcp',
        'digest' => 'setDigest',
        'enable' => 'setEnable',
        'ipfilter' => 'setIpfilter',
        'log_level_in' => 'setLogLevelIn',
        'log_level_out' => 'setLogLevelOut',
        'macfilter' => 'setMacfilter',
        'ndp' => 'setNdp',
        'policy_in' => 'setPolicyIn',
        'policy_out' => 'setPolicyOut',
        'radv' => 'setRadv',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delete' => 'getDelete',
        'dhcp' => 'getDhcp',
        'digest' => 'getDigest',
        'enable' => 'getEnable',
        'ipfilter' => 'getIpfilter',
        'log_level_in' => 'getLogLevelIn',
        'log_level_out' => 'getLogLevelOut',
        'macfilter' => 'getMacfilter',
        'ndp' => 'getNdp',
        'policy_in' => 'getPolicyIn',
        'policy_out' => 'getPolicyOut',
        'radv' => 'getRadv',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('delete', $data ?? [], null);
        
        $this->setIfExists('dhcp', $data ?? [], 0);
        
        $this->setIfExists('digest', $data ?? [], null);
        
        $this->setIfExists('enable', $data ?? [], 0);
        
        $this->setIfExists('ipfilter', $data ?? [], null);
        
        $this->setIfExists('log_level_in', $data ?? [], null);
        
        $this->setIfExists('log_level_out', $data ?? [], null);
        
        $this->setIfExists('macfilter', $data ?? [], 1);
        
        $this->setIfExists('ndp', $data ?? [], 1);
        
        $this->setIfExists('policy_in', $data ?? [], null);
        
        $this->setIfExists('policy_out', $data ?? [], null);
        
        $this->setIfExists('radv', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        if (!is_null($this->container['digest']) && (mb_strlen($this->container['digest']) > 64)) {
            $invalidProperties[] = "invalid value for 'digest', the character length must be smaller than or equal to 64.";
        }

        
        
        
        
        
        
        
        
        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets delete
     *
     * @return string|null
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param string|null $delete A list of settings you want to delete.
     *
     * @return self
     */
    public function setDelete($delete)
    {
        if (is_null($delete)) {
            throw new \InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }
    

    /**
     * Gets dhcp
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getDhcp()
    {
        return $this->container['dhcp'];
    }

    /**
     * Sets dhcp
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $dhcp Enable DHCP.
     *
     * @return self
     */
    public function setDhcp($dhcp)
    {
        if (is_null($dhcp)) {
            throw new \InvalidArgumentException('non-nullable dhcp cannot be null');
        }
        $this->container['dhcp'] = $dhcp;

        return $this;
    }
    

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }
        if ((mb_strlen($digest) > 64)) {
            throw new \InvalidArgumentException('invalid length for $digest when calling LxcSetOptionsRequest., must be smaller than or equal to 64.');
        }

        $this->container['digest'] = $digest;

        return $this;
    }
    

    /**
     * Gets enable
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getEnable()
    {
        return $this->container['enable'];
    }

    /**
     * Sets enable
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $enable Enable/disable firewall rules.
     *
     * @return self
     */
    public function setEnable($enable)
    {
        if (is_null($enable)) {
            throw new \InvalidArgumentException('non-nullable enable cannot be null');
        }
        $this->container['enable'] = $enable;

        return $this;
    }
    

    /**
     * Gets ipfilter
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getIpfilter()
    {
        return $this->container['ipfilter'];
    }

    /**
     * Sets ipfilter
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $ipfilter Enable default IP filters. This is equivalent to adding an empty ipfilter-net<id> ipset for every interface. Such ipsets implicitly contain sane default restrictions such as restricting IPv6 link local addresses to the one derived from the interface's MAC address. For containers the configured IP addresses will be implicitly added.
     *
     * @return self
     */
    public function setIpfilter($ipfilter)
    {
        if (is_null($ipfilter)) {
            throw new \InvalidArgumentException('non-nullable ipfilter cannot be null');
        }
        $this->container['ipfilter'] = $ipfilter;

        return $this;
    }
    

    /**
     * Gets log_level_in
     *
     * @return \ClientApi\PveClient\Model\PveLogEnum|null
     */
    public function getLogLevelIn()
    {
        return $this->container['log_level_in'];
    }

    /**
     * Sets log_level_in
     *
     * @param \ClientApi\PveClient\Model\PveLogEnum|null $log_level_in Log level for incoming traffic.
     *
     * @return self
     */
    public function setLogLevelIn($log_level_in)
    {
        if (is_null($log_level_in)) {
            throw new \InvalidArgumentException('non-nullable log_level_in cannot be null');
        }
        $this->container['log_level_in'] = $log_level_in;

        return $this;
    }
    

    /**
     * Gets log_level_out
     *
     * @return \ClientApi\PveClient\Model\PveLogEnum|null
     */
    public function getLogLevelOut()
    {
        return $this->container['log_level_out'];
    }

    /**
     * Sets log_level_out
     *
     * @param \ClientApi\PveClient\Model\PveLogEnum|null $log_level_out Log level for outgoing traffic.
     *
     * @return self
     */
    public function setLogLevelOut($log_level_out)
    {
        if (is_null($log_level_out)) {
            throw new \InvalidArgumentException('non-nullable log_level_out cannot be null');
        }
        $this->container['log_level_out'] = $log_level_out;

        return $this;
    }
    

    /**
     * Gets macfilter
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getMacfilter()
    {
        return $this->container['macfilter'];
    }

    /**
     * Sets macfilter
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $macfilter Enable/disable MAC address filter.
     *
     * @return self
     */
    public function setMacfilter($macfilter)
    {
        if (is_null($macfilter)) {
            throw new \InvalidArgumentException('non-nullable macfilter cannot be null');
        }
        $this->container['macfilter'] = $macfilter;

        return $this;
    }
    

    /**
     * Gets ndp
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getNdp()
    {
        return $this->container['ndp'];
    }

    /**
     * Sets ndp
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $ndp Enable NDP (Neighbor Discovery Protocol).
     *
     * @return self
     */
    public function setNdp($ndp)
    {
        if (is_null($ndp)) {
            throw new \InvalidArgumentException('non-nullable ndp cannot be null');
        }
        $this->container['ndp'] = $ndp;

        return $this;
    }
    

    /**
     * Gets policy_in
     *
     * @return \ClientApi\PveClient\Model\PvePolicyInEnum|null
     */
    public function getPolicyIn()
    {
        return $this->container['policy_in'];
    }

    /**
     * Sets policy_in
     *
     * @param \ClientApi\PveClient\Model\PvePolicyInEnum|null $policy_in Input policy.
     *
     * @return self
     */
    public function setPolicyIn($policy_in)
    {
        if (is_null($policy_in)) {
            throw new \InvalidArgumentException('non-nullable policy_in cannot be null');
        }
        $this->container['policy_in'] = $policy_in;

        return $this;
    }
    

    /**
     * Gets policy_out
     *
     * @return \ClientApi\PveClient\Model\PvePolicyInEnum|null
     */
    public function getPolicyOut()
    {
        return $this->container['policy_out'];
    }

    /**
     * Sets policy_out
     *
     * @param \ClientApi\PveClient\Model\PvePolicyInEnum|null $policy_out Output policy.
     *
     * @return self
     */
    public function setPolicyOut($policy_out)
    {
        if (is_null($policy_out)) {
            throw new \InvalidArgumentException('non-nullable policy_out cannot be null');
        }
        $this->container['policy_out'] = $policy_out;

        return $this;
    }
    

    /**
     * Gets radv
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getRadv()
    {
        return $this->container['radv'];
    }

    /**
     * Sets radv
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $radv Allow sending Router Advertisement.
     *
     * @return self
     */
    public function setRadv($radv)
    {
        if (is_null($radv)) {
            throw new \InvalidArgumentException('non-nullable radv cannot be null');
        }
        $this->container['radv'] = $radv;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



