<?php
/**
 * NodesStorageGetContentResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * NodesStorageGetContentResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodesStorageGetContentResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodesStorageGetContentResponse_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ctime' => 'int',
        'encrypted' => 'string',
        'format' => 'string',
        'notes' => 'string',
        'parent' => 'string',
        'protected' => '\ClientApi\PveClient\Model\PveBoolean',
        'size' => 'int',
        'used' => 'int',
        'verification' => '\ClientApi\PveClient\Model\NodesStorageGetContentResponseDataInnerVerification',
        'vmid' => 'int',
        'volid' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ctime' => 'int64',
        'encrypted' => null,
        'format' => null,
        'notes' => null,
        'parent' => null,
        'protected' => null,
        'size' => 'int64',
        'used' => 'int64',
        'verification' => null,
        'vmid' => 'int64',
        'volid' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ctime' => false,
        'encrypted' => false,
        'format' => false,
        'notes' => false,
        'parent' => false,
        'protected' => false,
        'size' => false,
        'used' => false,
        'verification' => false,
        'vmid' => false,
        'volid' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ctime' => 'ctime',
        'encrypted' => 'encrypted',
        'format' => 'format',
        'notes' => 'notes',
        'parent' => 'parent',
        'protected' => 'protected',
        'size' => 'size',
        'used' => 'used',
        'verification' => 'verification',
        'vmid' => 'vmid',
        'volid' => 'volid',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ctime' => 'setCtime',
        'encrypted' => 'setEncrypted',
        'format' => 'setFormat',
        'notes' => 'setNotes',
        'parent' => 'setParent',
        'protected' => 'setProtected',
        'size' => 'setSize',
        'used' => 'setUsed',
        'verification' => 'setVerification',
        'vmid' => 'setVmid',
        'volid' => 'setVolid',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ctime' => 'getCtime',
        'encrypted' => 'getEncrypted',
        'format' => 'getFormat',
        'notes' => 'getNotes',
        'parent' => 'getParent',
        'protected' => 'getProtected',
        'size' => 'getSize',
        'used' => 'getUsed',
        'verification' => 'getVerification',
        'vmid' => 'getVmid',
        'volid' => 'getVolid',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('ctime', $data ?? [], null);
        
        $this->setIfExists('encrypted', $data ?? [], null);
        
        $this->setIfExists('format', $data ?? [], null);
        
        $this->setIfExists('notes', $data ?? [], null);
        
        $this->setIfExists('parent', $data ?? [], null);
        
        $this->setIfExists('protected', $data ?? [], null);
        
        $this->setIfExists('size', $data ?? [], null);
        
        $this->setIfExists('used', $data ?? [], null);
        
        $this->setIfExists('verification', $data ?? [], null);
        
        $this->setIfExists('vmid', $data ?? [], null);
        
        $this->setIfExists('volid', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if (!is_null($this->container['ctime']) && ($this->container['ctime'] < 0)) {
            $invalidProperties[] = "invalid value for 'ctime', must be bigger than or equal to 0.";
        }

        
        
        if ($this->container['format'] === null) {
            $invalidProperties[] = "'format' can't be null";
        }
        
        
        
        
        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        
        
        
        
        if ($this->container['volid'] === null) {
            $invalidProperties[] = "'volid' can't be null";
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets ctime
     *
     * @return int|null
     */
    public function getCtime()
    {
        return $this->container['ctime'];
    }

    /**
     * Sets ctime
     *
     * @param int|null $ctime Creation time (seconds since the UNIX Epoch).
     *
     * @return self
     */
    public function setCtime($ctime)
    {
        if (is_null($ctime)) {
            throw new \InvalidArgumentException('non-nullable ctime cannot be null');
        }

        if (($ctime < 0)) {
            throw new \InvalidArgumentException('invalid value for $ctime when calling NodesStorageGetContentResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['ctime'] = $ctime;

        return $this;
    }
    

    /**
     * Gets encrypted
     *
     * @return string|null
     */
    public function getEncrypted()
    {
        return $this->container['encrypted'];
    }

    /**
     * Sets encrypted
     *
     * @param string|null $encrypted If whole backup is encrypted, value is the fingerprint or '1'  if encrypted. Only useful for the Proxmox Backup Server storage type.
     *
     * @return self
     */
    public function setEncrypted($encrypted)
    {
        if (is_null($encrypted)) {
            throw new \InvalidArgumentException('non-nullable encrypted cannot be null');
        }
        $this->container['encrypted'] = $encrypted;

        return $this;
    }
    

    /**
     * Gets format
     *
     * @return string
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param string $format Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...)
     *
     * @return self
     */
    public function setFormat($format)
    {
        if (is_null($format)) {
            throw new \InvalidArgumentException('non-nullable format cannot be null');
        }
        $this->container['format'] = $format;

        return $this;
    }
    

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes Optional notes. If they contain multiple lines, only the first one is returned here.
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            throw new \InvalidArgumentException('non-nullable notes cannot be null');
        }
        $this->container['notes'] = $notes;

        return $this;
    }
    

    /**
     * Gets parent
     *
     * @return string|null
     */
    public function getParent()
    {
        return $this->container['parent'];
    }

    /**
     * Sets parent
     *
     * @param string|null $parent Volume identifier of parent (for linked cloned).
     *
     * @return self
     */
    public function setParent($parent)
    {
        if (is_null($parent)) {
            throw new \InvalidArgumentException('non-nullable parent cannot be null');
        }
        $this->container['parent'] = $parent;

        return $this;
    }
    

    /**
     * Gets protected
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getProtected()
    {
        return $this->container['protected'];
    }

    /**
     * Sets protected
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $protected Protection status. Currently only supported for backups.
     *
     * @return self
     */
    public function setProtected($protected)
    {
        if (is_null($protected)) {
            throw new \InvalidArgumentException('non-nullable protected cannot be null');
        }
        $this->container['protected'] = $protected;

        return $this;
    }
    

    /**
     * Gets size
     *
     * @return int
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int $size Volume size in bytes.
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }
    

    /**
     * Gets used
     *
     * @return int|null
     */
    public function getUsed()
    {
        return $this->container['used'];
    }

    /**
     * Sets used
     *
     * @param int|null $used Used space. Please note that most storage plugins do not report anything useful here.
     *
     * @return self
     */
    public function setUsed($used)
    {
        if (is_null($used)) {
            throw new \InvalidArgumentException('non-nullable used cannot be null');
        }
        $this->container['used'] = $used;

        return $this;
    }
    

    /**
     * Gets verification
     *
     * @return \ClientApi\PveClient\Model\NodesStorageGetContentResponseDataInnerVerification|null
     */
    public function getVerification()
    {
        return $this->container['verification'];
    }

    /**
     * Sets verification
     *
     * @param \ClientApi\PveClient\Model\NodesStorageGetContentResponseDataInnerVerification|null $verification verification
     *
     * @return self
     */
    public function setVerification($verification)
    {
        if (is_null($verification)) {
            throw new \InvalidArgumentException('non-nullable verification cannot be null');
        }
        $this->container['verification'] = $verification;

        return $this;
    }
    

    /**
     * Gets vmid
     *
     * @return int|null
     */
    public function getVmid()
    {
        return $this->container['vmid'];
    }

    /**
     * Sets vmid
     *
     * @param int|null $vmid Associated Owner VMID.
     *
     * @return self
     */
    public function setVmid($vmid)
    {
        if (is_null($vmid)) {
            throw new \InvalidArgumentException('non-nullable vmid cannot be null');
        }
        $this->container['vmid'] = $vmid;

        return $this;
    }
    

    /**
     * Gets volid
     *
     * @return string
     */
    public function getVolid()
    {
        return $this->container['volid'];
    }

    /**
     * Sets volid
     *
     * @param string $volid Volume identifier.
     *
     * @return self
     */
    public function setVolid($volid)
    {
        if (is_null($volid)) {
            throw new \InvalidArgumentException('non-nullable volid cannot be null');
        }
        $this->container['volid'] = $volid;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



