<?php
/**
 * NodesStorageUploadRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * NodesStorageUploadRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodesStorageUploadRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodesStorageUploadRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'checksum' => 'string',
        'checksum_algorithm' => '\ClientApi\PveClient\Model\PveChecksumAlgorithmEnum',
        'content' => '\ClientApi\PveClient\Model\PveContentEnum',
        'filename' => 'string',
        'tmpfilename' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'checksum' => null,
        'checksum_algorithm' => null,
        'content' => null,
        'filename' => null,
        'tmpfilename' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'checksum' => false,
        'checksum_algorithm' => false,
        'content' => false,
        'filename' => false,
        'tmpfilename' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checksum' => 'checksum',
        'checksum_algorithm' => 'checksum-algorithm',
        'content' => 'content',
        'filename' => 'filename',
        'tmpfilename' => 'tmpfilename',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checksum' => 'setChecksum',
        'checksum_algorithm' => 'setChecksumAlgorithm',
        'content' => 'setContent',
        'filename' => 'setFilename',
        'tmpfilename' => 'setTmpfilename',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checksum' => 'getChecksum',
        'checksum_algorithm' => 'getChecksumAlgorithm',
        'content' => 'getContent',
        'filename' => 'getFilename',
        'tmpfilename' => 'getTmpfilename',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('checksum', $data ?? [], null);
        
        $this->setIfExists('checksum_algorithm', $data ?? [], null);
        
        $this->setIfExists('content', $data ?? [], null);
        
        $this->setIfExists('filename', $data ?? [], null);
        
        $this->setIfExists('tmpfilename', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        
        if ($this->container['filename'] === null) {
            $invalidProperties[] = "'filename' can't be null";
        }
        if ((mb_strlen($this->container['filename']) > 255)) {
            $invalidProperties[] = "invalid value for 'filename', the character length must be smaller than or equal to 255.";
        }

        
        if (!is_null($this->container['tmpfilename']) && !preg_match("/var/tmp/pveupload-[0-9a-f]+", $this->container['tmpfilename'])) {
            $invalidProperties[] = "invalid value for 'tmpfilename', must be conform to the pattern /var/tmp/pveupload-[0-9a-f]+.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets checksum
     *
     * @return string|null
     */
    public function getChecksum()
    {
        return $this->container['checksum'];
    }

    /**
     * Sets checksum
     *
     * @param string|null $checksum The expected checksum of the file.
     *
     * @return self
     */
    public function setChecksum($checksum)
    {
        if (is_null($checksum)) {
            throw new \InvalidArgumentException('non-nullable checksum cannot be null');
        }
        $this->container['checksum'] = $checksum;

        return $this;
    }
    

    /**
     * Gets checksum_algorithm
     *
     * @return \ClientApi\PveClient\Model\PveChecksumAlgorithmEnum|null
     */
    public function getChecksumAlgorithm()
    {
        return $this->container['checksum_algorithm'];
    }

    /**
     * Sets checksum_algorithm
     *
     * @param \ClientApi\PveClient\Model\PveChecksumAlgorithmEnum|null $checksum_algorithm The algorithm to calculate the checksum of the file.
     *
     * @return self
     */
    public function setChecksumAlgorithm($checksum_algorithm)
    {
        if (is_null($checksum_algorithm)) {
            throw new \InvalidArgumentException('non-nullable checksum_algorithm cannot be null');
        }
        $this->container['checksum_algorithm'] = $checksum_algorithm;

        return $this;
    }
    

    /**
     * Gets content
     *
     * @return \ClientApi\PveClient\Model\PveContentEnum
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \ClientApi\PveClient\Model\PveContentEnum $content Content type.
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }
    

    /**
     * Gets filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string $filename The name of the file to create. Caution: This will be normalized!
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            throw new \InvalidArgumentException('non-nullable filename cannot be null');
        }
        if ((mb_strlen($filename) > 255)) {
            throw new \InvalidArgumentException('invalid length for $filename when calling NodesStorageUploadRequest., must be smaller than or equal to 255.');
        }

        $this->container['filename'] = $filename;

        return $this;
    }
    

    /**
     * Gets tmpfilename
     *
     * @return string|null
     */
    public function getTmpfilename()
    {
        return $this->container['tmpfilename'];
    }

    /**
     * Sets tmpfilename
     *
     * @param string|null $tmpfilename The source file name. This parameter is usually set by the REST handler. You can only overwrite it when connecting to the trusted port on localhost.
     *
     * @return self
     */
    public function setTmpfilename($tmpfilename)
    {
        if (is_null($tmpfilename)) {
            throw new \InvalidArgumentException('non-nullable tmpfilename cannot be null');
        }

        if ((!preg_match("/var/tmp/pveupload-[0-9a-f]+", ObjectSerializer::toString($tmpfilename)))) {
            throw new \InvalidArgumentException("invalid value for \$tmpfilename when calling NodesStorageUploadRequest., must conform to the pattern /var/tmp/pveupload-[0-9a-f]+.");
        }

        $this->container['tmpfilename'] = $tmpfilename;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



