<?php
/**
 * PveDiskEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveDiskEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PveDiskEnum
{
    /**
     * Possible values of this enum
     */
    public const IDE0 = 'ide0';

    public const IDE1 = 'ide1';

    public const IDE2 = 'ide2';

    public const IDE3 = 'ide3';

    public const SCSI0 = 'scsi0';

    public const SCSI1 = 'scsi1';

    public const SCSI2 = 'scsi2';

    public const SCSI3 = 'scsi3';

    public const SCSI4 = 'scsi4';

    public const SCSI5 = 'scsi5';

    public const SCSI6 = 'scsi6';

    public const SCSI7 = 'scsi7';

    public const SCSI8 = 'scsi8';

    public const SCSI9 = 'scsi9';

    public const SCSI10 = 'scsi10';

    public const SCSI11 = 'scsi11';

    public const SCSI12 = 'scsi12';

    public const SCSI13 = 'scsi13';

    public const SCSI14 = 'scsi14';

    public const SCSI15 = 'scsi15';

    public const SCSI16 = 'scsi16';

    public const SCSI17 = 'scsi17';

    public const SCSI18 = 'scsi18';

    public const SCSI19 = 'scsi19';

    public const SCSI20 = 'scsi20';

    public const SCSI21 = 'scsi21';

    public const SCSI22 = 'scsi22';

    public const SCSI23 = 'scsi23';

    public const SCSI24 = 'scsi24';

    public const SCSI25 = 'scsi25';

    public const SCSI26 = 'scsi26';

    public const SCSI27 = 'scsi27';

    public const SCSI28 = 'scsi28';

    public const SCSI29 = 'scsi29';

    public const SCSI30 = 'scsi30';

    public const VIRTIO0 = 'virtio0';

    public const VIRTIO1 = 'virtio1';

    public const VIRTIO2 = 'virtio2';

    public const VIRTIO3 = 'virtio3';

    public const VIRTIO4 = 'virtio4';

    public const VIRTIO5 = 'virtio5';

    public const VIRTIO6 = 'virtio6';

    public const VIRTIO7 = 'virtio7';

    public const VIRTIO8 = 'virtio8';

    public const VIRTIO9 = 'virtio9';

    public const VIRTIO10 = 'virtio10';

    public const VIRTIO11 = 'virtio11';

    public const VIRTIO12 = 'virtio12';

    public const VIRTIO13 = 'virtio13';

    public const VIRTIO14 = 'virtio14';

    public const VIRTIO15 = 'virtio15';

    public const SATA0 = 'sata0';

    public const SATA1 = 'sata1';

    public const SATA2 = 'sata2';

    public const SATA3 = 'sata3';

    public const SATA4 = 'sata4';

    public const SATA5 = 'sata5';

    public const EFIDISK0 = 'efidisk0';

    public const TPMSTATE0 = 'tpmstate0';

    public const UNUSED0 = 'unused0';

    public const UNUSED1 = 'unused1';

    public const UNUSED2 = 'unused2';

    public const UNUSED3 = 'unused3';

    public const UNUSED4 = 'unused4';

    public const UNUSED5 = 'unused5';

    public const UNUSED6 = 'unused6';

    public const UNUSED7 = 'unused7';

    public const UNUSED8 = 'unused8';

    public const UNUSED9 = 'unused9';

    public const UNUSED10 = 'unused10';

    public const UNUSED11 = 'unused11';

    public const UNUSED12 = 'unused12';

    public const UNUSED13 = 'unused13';

    public const UNUSED14 = 'unused14';

    public const UNUSED15 = 'unused15';

    public const UNUSED16 = 'unused16';

    public const UNUSED17 = 'unused17';

    public const UNUSED18 = 'unused18';

    public const UNUSED19 = 'unused19';

    public const UNUSED20 = 'unused20';

    public const UNUSED21 = 'unused21';

    public const UNUSED22 = 'unused22';

    public const UNUSED23 = 'unused23';

    public const UNUSED24 = 'unused24';

    public const UNUSED25 = 'unused25';

    public const UNUSED26 = 'unused26';

    public const UNUSED27 = 'unused27';

    public const UNUSED28 = 'unused28';

    public const UNUSED29 = 'unused29';

    public const UNUSED30 = 'unused30';

    public const UNUSED31 = 'unused31';

    public const UNUSED32 = 'unused32';

    public const UNUSED33 = 'unused33';

    public const UNUSED34 = 'unused34';

    public const UNUSED35 = 'unused35';

    public const UNUSED36 = 'unused36';

    public const UNUSED37 = 'unused37';

    public const UNUSED38 = 'unused38';

    public const UNUSED39 = 'unused39';

    public const UNUSED40 = 'unused40';

    public const UNUSED41 = 'unused41';

    public const UNUSED42 = 'unused42';

    public const UNUSED43 = 'unused43';

    public const UNUSED44 = 'unused44';

    public const UNUSED45 = 'unused45';

    public const UNUSED46 = 'unused46';

    public const UNUSED47 = 'unused47';

    public const UNUSED48 = 'unused48';

    public const UNUSED49 = 'unused49';

    public const UNUSED50 = 'unused50';

    public const UNUSED51 = 'unused51';

    public const UNUSED52 = 'unused52';

    public const UNUSED53 = 'unused53';

    public const UNUSED54 = 'unused54';

    public const UNUSED55 = 'unused55';

    public const UNUSED56 = 'unused56';

    public const UNUSED57 = 'unused57';

    public const UNUSED58 = 'unused58';

    public const UNUSED59 = 'unused59';

    public const UNUSED60 = 'unused60';

    public const UNUSED61 = 'unused61';

    public const UNUSED62 = 'unused62';

    public const UNUSED63 = 'unused63';

    public const UNUSED64 = 'unused64';

    public const UNUSED65 = 'unused65';

    public const UNUSED66 = 'unused66';

    public const UNUSED67 = 'unused67';

    public const UNUSED68 = 'unused68';

    public const UNUSED69 = 'unused69';

    public const UNUSED70 = 'unused70';

    public const UNUSED71 = 'unused71';

    public const UNUSED72 = 'unused72';

    public const UNUSED73 = 'unused73';

    public const UNUSED74 = 'unused74';

    public const UNUSED75 = 'unused75';

    public const UNUSED76 = 'unused76';

    public const UNUSED77 = 'unused77';

    public const UNUSED78 = 'unused78';

    public const UNUSED79 = 'unused79';

    public const UNUSED80 = 'unused80';

    public const UNUSED81 = 'unused81';

    public const UNUSED82 = 'unused82';

    public const UNUSED83 = 'unused83';

    public const UNUSED84 = 'unused84';

    public const UNUSED85 = 'unused85';

    public const UNUSED86 = 'unused86';

    public const UNUSED87 = 'unused87';

    public const UNUSED88 = 'unused88';

    public const UNUSED89 = 'unused89';

    public const UNUSED90 = 'unused90';

    public const UNUSED91 = 'unused91';

    public const UNUSED92 = 'unused92';

    public const UNUSED93 = 'unused93';

    public const UNUSED94 = 'unused94';

    public const UNUSED95 = 'unused95';

    public const UNUSED96 = 'unused96';

    public const UNUSED97 = 'unused97';

    public const UNUSED98 = 'unused98';

    public const UNUSED99 = 'unused99';

    public const UNUSED100 = 'unused100';

    public const UNUSED101 = 'unused101';

    public const UNUSED102 = 'unused102';

    public const UNUSED103 = 'unused103';

    public const UNUSED104 = 'unused104';

    public const UNUSED105 = 'unused105';

    public const UNUSED106 = 'unused106';

    public const UNUSED107 = 'unused107';

    public const UNUSED108 = 'unused108';

    public const UNUSED109 = 'unused109';

    public const UNUSED110 = 'unused110';

    public const UNUSED111 = 'unused111';

    public const UNUSED112 = 'unused112';

    public const UNUSED113 = 'unused113';

    public const UNUSED114 = 'unused114';

    public const UNUSED115 = 'unused115';

    public const UNUSED116 = 'unused116';

    public const UNUSED117 = 'unused117';

    public const UNUSED118 = 'unused118';

    public const UNUSED119 = 'unused119';

    public const UNUSED120 = 'unused120';

    public const UNUSED121 = 'unused121';

    public const UNUSED122 = 'unused122';

    public const UNUSED123 = 'unused123';

    public const UNUSED124 = 'unused124';

    public const UNUSED125 = 'unused125';

    public const UNUSED126 = 'unused126';

    public const UNUSED127 = 'unused127';

    public const UNUSED128 = 'unused128';

    public const UNUSED129 = 'unused129';

    public const UNUSED130 = 'unused130';

    public const UNUSED131 = 'unused131';

    public const UNUSED132 = 'unused132';

    public const UNUSED133 = 'unused133';

    public const UNUSED134 = 'unused134';

    public const UNUSED135 = 'unused135';

    public const UNUSED136 = 'unused136';

    public const UNUSED137 = 'unused137';

    public const UNUSED138 = 'unused138';

    public const UNUSED139 = 'unused139';

    public const UNUSED140 = 'unused140';

    public const UNUSED141 = 'unused141';

    public const UNUSED142 = 'unused142';

    public const UNUSED143 = 'unused143';

    public const UNUSED144 = 'unused144';

    public const UNUSED145 = 'unused145';

    public const UNUSED146 = 'unused146';

    public const UNUSED147 = 'unused147';

    public const UNUSED148 = 'unused148';

    public const UNUSED149 = 'unused149';

    public const UNUSED150 = 'unused150';

    public const UNUSED151 = 'unused151';

    public const UNUSED152 = 'unused152';

    public const UNUSED153 = 'unused153';

    public const UNUSED154 = 'unused154';

    public const UNUSED155 = 'unused155';

    public const UNUSED156 = 'unused156';

    public const UNUSED157 = 'unused157';

    public const UNUSED158 = 'unused158';

    public const UNUSED159 = 'unused159';

    public const UNUSED160 = 'unused160';

    public const UNUSED161 = 'unused161';

    public const UNUSED162 = 'unused162';

    public const UNUSED163 = 'unused163';

    public const UNUSED164 = 'unused164';

    public const UNUSED165 = 'unused165';

    public const UNUSED166 = 'unused166';

    public const UNUSED167 = 'unused167';

    public const UNUSED168 = 'unused168';

    public const UNUSED169 = 'unused169';

    public const UNUSED170 = 'unused170';

    public const UNUSED171 = 'unused171';

    public const UNUSED172 = 'unused172';

    public const UNUSED173 = 'unused173';

    public const UNUSED174 = 'unused174';

    public const UNUSED175 = 'unused175';

    public const UNUSED176 = 'unused176';

    public const UNUSED177 = 'unused177';

    public const UNUSED178 = 'unused178';

    public const UNUSED179 = 'unused179';

    public const UNUSED180 = 'unused180';

    public const UNUSED181 = 'unused181';

    public const UNUSED182 = 'unused182';

    public const UNUSED183 = 'unused183';

    public const UNUSED184 = 'unused184';

    public const UNUSED185 = 'unused185';

    public const UNUSED186 = 'unused186';

    public const UNUSED187 = 'unused187';

    public const UNUSED188 = 'unused188';

    public const UNUSED189 = 'unused189';

    public const UNUSED190 = 'unused190';

    public const UNUSED191 = 'unused191';

    public const UNUSED192 = 'unused192';

    public const UNUSED193 = 'unused193';

    public const UNUSED194 = 'unused194';

    public const UNUSED195 = 'unused195';

    public const UNUSED196 = 'unused196';

    public const UNUSED197 = 'unused197';

    public const UNUSED198 = 'unused198';

    public const UNUSED199 = 'unused199';

    public const UNUSED200 = 'unused200';

    public const UNUSED201 = 'unused201';

    public const UNUSED202 = 'unused202';

    public const UNUSED203 = 'unused203';

    public const UNUSED204 = 'unused204';

    public const UNUSED205 = 'unused205';

    public const UNUSED206 = 'unused206';

    public const UNUSED207 = 'unused207';

    public const UNUSED208 = 'unused208';

    public const UNUSED209 = 'unused209';

    public const UNUSED210 = 'unused210';

    public const UNUSED211 = 'unused211';

    public const UNUSED212 = 'unused212';

    public const UNUSED213 = 'unused213';

    public const UNUSED214 = 'unused214';

    public const UNUSED215 = 'unused215';

    public const UNUSED216 = 'unused216';

    public const UNUSED217 = 'unused217';

    public const UNUSED218 = 'unused218';

    public const UNUSED219 = 'unused219';

    public const UNUSED220 = 'unused220';

    public const UNUSED221 = 'unused221';

    public const UNUSED222 = 'unused222';

    public const UNUSED223 = 'unused223';

    public const UNUSED224 = 'unused224';

    public const UNUSED225 = 'unused225';

    public const UNUSED226 = 'unused226';

    public const UNUSED227 = 'unused227';

    public const UNUSED228 = 'unused228';

    public const UNUSED229 = 'unused229';

    public const UNUSED230 = 'unused230';

    public const UNUSED231 = 'unused231';

    public const UNUSED232 = 'unused232';

    public const UNUSED233 = 'unused233';

    public const UNUSED234 = 'unused234';

    public const UNUSED235 = 'unused235';

    public const UNUSED236 = 'unused236';

    public const UNUSED237 = 'unused237';

    public const UNUSED238 = 'unused238';

    public const UNUSED239 = 'unused239';

    public const UNUSED240 = 'unused240';

    public const UNUSED241 = 'unused241';

    public const UNUSED242 = 'unused242';

    public const UNUSED243 = 'unused243';

    public const UNUSED244 = 'unused244';

    public const UNUSED245 = 'unused245';

    public const UNUSED246 = 'unused246';

    public const UNUSED247 = 'unused247';

    public const UNUSED248 = 'unused248';

    public const UNUSED249 = 'unused249';

    public const UNUSED250 = 'unused250';

    public const UNUSED251 = 'unused251';

    public const UNUSED252 = 'unused252';

    public const UNUSED253 = 'unused253';

    public const UNUSED254 = 'unused254';

    public const UNUSED255 = 'unused255';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IDE0,
            self::IDE1,
            self::IDE2,
            self::IDE3,
            self::SCSI0,
            self::SCSI1,
            self::SCSI2,
            self::SCSI3,
            self::SCSI4,
            self::SCSI5,
            self::SCSI6,
            self::SCSI7,
            self::SCSI8,
            self::SCSI9,
            self::SCSI10,
            self::SCSI11,
            self::SCSI12,
            self::SCSI13,
            self::SCSI14,
            self::SCSI15,
            self::SCSI16,
            self::SCSI17,
            self::SCSI18,
            self::SCSI19,
            self::SCSI20,
            self::SCSI21,
            self::SCSI22,
            self::SCSI23,
            self::SCSI24,
            self::SCSI25,
            self::SCSI26,
            self::SCSI27,
            self::SCSI28,
            self::SCSI29,
            self::SCSI30,
            self::VIRTIO0,
            self::VIRTIO1,
            self::VIRTIO2,
            self::VIRTIO3,
            self::VIRTIO4,
            self::VIRTIO5,
            self::VIRTIO6,
            self::VIRTIO7,
            self::VIRTIO8,
            self::VIRTIO9,
            self::VIRTIO10,
            self::VIRTIO11,
            self::VIRTIO12,
            self::VIRTIO13,
            self::VIRTIO14,
            self::VIRTIO15,
            self::SATA0,
            self::SATA1,
            self::SATA2,
            self::SATA3,
            self::SATA4,
            self::SATA5,
            self::EFIDISK0,
            self::TPMSTATE0,
            self::UNUSED0,
            self::UNUSED1,
            self::UNUSED2,
            self::UNUSED3,
            self::UNUSED4,
            self::UNUSED5,
            self::UNUSED6,
            self::UNUSED7,
            self::UNUSED8,
            self::UNUSED9,
            self::UNUSED10,
            self::UNUSED11,
            self::UNUSED12,
            self::UNUSED13,
            self::UNUSED14,
            self::UNUSED15,
            self::UNUSED16,
            self::UNUSED17,
            self::UNUSED18,
            self::UNUSED19,
            self::UNUSED20,
            self::UNUSED21,
            self::UNUSED22,
            self::UNUSED23,
            self::UNUSED24,
            self::UNUSED25,
            self::UNUSED26,
            self::UNUSED27,
            self::UNUSED28,
            self::UNUSED29,
            self::UNUSED30,
            self::UNUSED31,
            self::UNUSED32,
            self::UNUSED33,
            self::UNUSED34,
            self::UNUSED35,
            self::UNUSED36,
            self::UNUSED37,
            self::UNUSED38,
            self::UNUSED39,
            self::UNUSED40,
            self::UNUSED41,
            self::UNUSED42,
            self::UNUSED43,
            self::UNUSED44,
            self::UNUSED45,
            self::UNUSED46,
            self::UNUSED47,
            self::UNUSED48,
            self::UNUSED49,
            self::UNUSED50,
            self::UNUSED51,
            self::UNUSED52,
            self::UNUSED53,
            self::UNUSED54,
            self::UNUSED55,
            self::UNUSED56,
            self::UNUSED57,
            self::UNUSED58,
            self::UNUSED59,
            self::UNUSED60,
            self::UNUSED61,
            self::UNUSED62,
            self::UNUSED63,
            self::UNUSED64,
            self::UNUSED65,
            self::UNUSED66,
            self::UNUSED67,
            self::UNUSED68,
            self::UNUSED69,
            self::UNUSED70,
            self::UNUSED71,
            self::UNUSED72,
            self::UNUSED73,
            self::UNUSED74,
            self::UNUSED75,
            self::UNUSED76,
            self::UNUSED77,
            self::UNUSED78,
            self::UNUSED79,
            self::UNUSED80,
            self::UNUSED81,
            self::UNUSED82,
            self::UNUSED83,
            self::UNUSED84,
            self::UNUSED85,
            self::UNUSED86,
            self::UNUSED87,
            self::UNUSED88,
            self::UNUSED89,
            self::UNUSED90,
            self::UNUSED91,
            self::UNUSED92,
            self::UNUSED93,
            self::UNUSED94,
            self::UNUSED95,
            self::UNUSED96,
            self::UNUSED97,
            self::UNUSED98,
            self::UNUSED99,
            self::UNUSED100,
            self::UNUSED101,
            self::UNUSED102,
            self::UNUSED103,
            self::UNUSED104,
            self::UNUSED105,
            self::UNUSED106,
            self::UNUSED107,
            self::UNUSED108,
            self::UNUSED109,
            self::UNUSED110,
            self::UNUSED111,
            self::UNUSED112,
            self::UNUSED113,
            self::UNUSED114,
            self::UNUSED115,
            self::UNUSED116,
            self::UNUSED117,
            self::UNUSED118,
            self::UNUSED119,
            self::UNUSED120,
            self::UNUSED121,
            self::UNUSED122,
            self::UNUSED123,
            self::UNUSED124,
            self::UNUSED125,
            self::UNUSED126,
            self::UNUSED127,
            self::UNUSED128,
            self::UNUSED129,
            self::UNUSED130,
            self::UNUSED131,
            self::UNUSED132,
            self::UNUSED133,
            self::UNUSED134,
            self::UNUSED135,
            self::UNUSED136,
            self::UNUSED137,
            self::UNUSED138,
            self::UNUSED139,
            self::UNUSED140,
            self::UNUSED141,
            self::UNUSED142,
            self::UNUSED143,
            self::UNUSED144,
            self::UNUSED145,
            self::UNUSED146,
            self::UNUSED147,
            self::UNUSED148,
            self::UNUSED149,
            self::UNUSED150,
            self::UNUSED151,
            self::UNUSED152,
            self::UNUSED153,
            self::UNUSED154,
            self::UNUSED155,
            self::UNUSED156,
            self::UNUSED157,
            self::UNUSED158,
            self::UNUSED159,
            self::UNUSED160,
            self::UNUSED161,
            self::UNUSED162,
            self::UNUSED163,
            self::UNUSED164,
            self::UNUSED165,
            self::UNUSED166,
            self::UNUSED167,
            self::UNUSED168,
            self::UNUSED169,
            self::UNUSED170,
            self::UNUSED171,
            self::UNUSED172,
            self::UNUSED173,
            self::UNUSED174,
            self::UNUSED175,
            self::UNUSED176,
            self::UNUSED177,
            self::UNUSED178,
            self::UNUSED179,
            self::UNUSED180,
            self::UNUSED181,
            self::UNUSED182,
            self::UNUSED183,
            self::UNUSED184,
            self::UNUSED185,
            self::UNUSED186,
            self::UNUSED187,
            self::UNUSED188,
            self::UNUSED189,
            self::UNUSED190,
            self::UNUSED191,
            self::UNUSED192,
            self::UNUSED193,
            self::UNUSED194,
            self::UNUSED195,
            self::UNUSED196,
            self::UNUSED197,
            self::UNUSED198,
            self::UNUSED199,
            self::UNUSED200,
            self::UNUSED201,
            self::UNUSED202,
            self::UNUSED203,
            self::UNUSED204,
            self::UNUSED205,
            self::UNUSED206,
            self::UNUSED207,
            self::UNUSED208,
            self::UNUSED209,
            self::UNUSED210,
            self::UNUSED211,
            self::UNUSED212,
            self::UNUSED213,
            self::UNUSED214,
            self::UNUSED215,
            self::UNUSED216,
            self::UNUSED217,
            self::UNUSED218,
            self::UNUSED219,
            self::UNUSED220,
            self::UNUSED221,
            self::UNUSED222,
            self::UNUSED223,
            self::UNUSED224,
            self::UNUSED225,
            self::UNUSED226,
            self::UNUSED227,
            self::UNUSED228,
            self::UNUSED229,
            self::UNUSED230,
            self::UNUSED231,
            self::UNUSED232,
            self::UNUSED233,
            self::UNUSED234,
            self::UNUSED235,
            self::UNUSED236,
            self::UNUSED237,
            self::UNUSED238,
            self::UNUSED239,
            self::UNUSED240,
            self::UNUSED241,
            self::UNUSED242,
            self::UNUSED243,
            self::UNUSED244,
            self::UNUSED245,
            self::UNUSED246,
            self::UNUSED247,
            self::UNUSED248,
            self::UNUSED249,
            self::UNUSED250,
            self::UNUSED251,
            self::UNUSED252,
            self::UNUSED253,
            self::UNUSED254,
            self::UNUSED255
        ];
    }
}


