<?php
/**
 * PveNotificationModeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveNotificationModeEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PveNotificationModeEnum
{
    /**
     * Possible values of this enum
     */
    public const AUTO = 'auto';

    public const LEGACY_SENDMAIL = 'legacy-sendmail';

    public const NOTIFICATION_SYSTEM = 'notification-system';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTO,
            self::LEGACY_SENDMAIL,
            self::NOTIFICATION_SYSTEM
        ];
    }
}


