<?php
/**
 * PveNodesDisksRaidlevelEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveNodesDisksRaidlevelEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PveNodesDisksRaidlevelEnum
{
    /**
     * Possible values of this enum
     */
    public const SINGLE = 'single';

    public const MIRROR = 'mirror';

    public const RAID10 = 'raid10';

    public const RAIDZ = 'raidz';

    public const RAIDZ2 = 'raidz2';

    public const RAIDZ3 = 'raidz3';

    public const DRAID = 'draid';

    public const DRAID2 = 'draid2';

    public const DRAID3 = 'draid3';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SINGLE,
            self::MIRROR,
            self::RAID10,
            self::RAIDZ,
            self::RAIDZ2,
            self::RAIDZ3,
            self::DRAID,
            self::DRAID2,
            self::DRAID3
        ];
    }
}


