<?php
/**
 * PveQemuSerialEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveQemuSerialEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PveQemuSerialEnum
{
    /**
     * Possible values of this enum
     */
    public const SERIAL0 = 'serial0';

    public const SERIAL1 = 'serial1';

    public const SERIAL2 = 'serial2';

    public const SERIAL3 = 'serial3';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SERIAL0,
            self::SERIAL1,
            self::SERIAL2,
            self::SERIAL3
        ];
    }
}


