<?php
/**
 * PveQemuCommandEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveQemuCommandEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PveQemuCommandEnum
{
    /**
     * Possible values of this enum
     */
    public const FSFREEZE_FREEZE = 'fsfreeze-freeze';

    public const FSFREEZE_STATUS = 'fsfreeze-status';

    public const FSFREEZE_THAW = 'fsfreeze-thaw';

    public const FSTRIM = 'fstrim';

    public const GET_FSINFO = 'get-fsinfo';

    public const GET_HOST_NAME = 'get-host-name';

    public const GET_MEMORY_BLOCK_INFO = 'get-memory-block-info';

    public const GET_MEMORY_BLOCKS = 'get-memory-blocks';

    public const GET_OSINFO = 'get-osinfo';

    public const GET_TIME = 'get-time';

    public const GET_TIMEZONE = 'get-timezone';

    public const GET_USERS = 'get-users';

    public const GET_VCPUS = 'get-vcpus';

    public const INFO = 'info';

    public const NETWORK_GET_INTERFACES = 'network-get-interfaces';

    public const PING = 'ping';

    public const SHUTDOWN = 'shutdown';

    public const SUSPEND_DISK = 'suspend-disk';

    public const SUSPEND_HYBRID = 'suspend-hybrid';

    public const SUSPEND_RAM = 'suspend-ram';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FSFREEZE_FREEZE,
            self::FSFREEZE_STATUS,
            self::FSFREEZE_THAW,
            self::FSTRIM,
            self::GET_FSINFO,
            self::GET_HOST_NAME,
            self::GET_MEMORY_BLOCK_INFO,
            self::GET_MEMORY_BLOCKS,
            self::GET_OSINFO,
            self::GET_TIME,
            self::GET_TIMEZONE,
            self::GET_USERS,
            self::GET_VCPUS,
            self::INFO,
            self::NETWORK_GET_INTERFACES,
            self::PING,
            self::SHUTDOWN,
            self::SUSPEND_DISK,
            self::SUSPEND_HYBRID,
            self::SUSPEND_RAM
        ];
    }
}


