<?php
/**
 * PveStoragePbsConfig
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * PveStoragePbsConfig Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PveStoragePbsConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PveStoragePbsConfig';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'server' => 'string',
        'datastore' => 'string',
        'namespace' => 'string',
        'port' => 'int',
        'nodes' => 'string',
        'disable' => '\ClientApi\PveClient\Model\PveBoolean',
        'content' => 'string',
        'username' => 'string',
        'password' => 'string',
        'encryption_key' => 'string',
        'master_pubkey' => 'string',
        'prune_backups' => 'string',
        'max_protected_backups' => 'int',
        'fingerprint' => 'string',
        'type' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'server' => 'pve-storage-server',
        'datastore' => null,
        'namespace' => null,
        'port' => null,
        'nodes' => 'pve-node-list',
        'disable' => null,
        'content' => 'pve-storage-content-list',
        'username' => null,
        'password' => null,
        'encryption_key' => null,
        'master_pubkey' => null,
        'prune_backups' => 'prune-backups',
        'max_protected_backups' => 'int64',
        'fingerprint' => null,
        'type' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'server' => false,
        'datastore' => false,
        'namespace' => false,
        'port' => false,
        'nodes' => false,
        'disable' => false,
        'content' => false,
        'username' => false,
        'password' => false,
        'encryption_key' => false,
        'master_pubkey' => false,
        'prune_backups' => false,
        'max_protected_backups' => false,
        'fingerprint' => false,
        'type' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'server' => 'server',
        'datastore' => 'datastore',
        'namespace' => 'namespace',
        'port' => 'port',
        'nodes' => 'nodes',
        'disable' => 'disable',
        'content' => 'content',
        'username' => 'username',
        'password' => 'password',
        'encryption_key' => 'encryption-key',
        'master_pubkey' => 'master-pubkey',
        'prune_backups' => 'prune-backups',
        'max_protected_backups' => 'max-protected-backups',
        'fingerprint' => 'fingerprint',
        'type' => 'type',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'server' => 'setServer',
        'datastore' => 'setDatastore',
        'namespace' => 'setNamespace',
        'port' => 'setPort',
        'nodes' => 'setNodes',
        'disable' => 'setDisable',
        'content' => 'setContent',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'encryption_key' => 'setEncryptionKey',
        'master_pubkey' => 'setMasterPubkey',
        'prune_backups' => 'setPruneBackups',
        'max_protected_backups' => 'setMaxProtectedBackups',
        'fingerprint' => 'setFingerprint',
        'type' => 'setType',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'server' => 'getServer',
        'datastore' => 'getDatastore',
        'namespace' => 'getNamespace',
        'port' => 'getPort',
        'nodes' => 'getNodes',
        'disable' => 'getDisable',
        'content' => 'getContent',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'encryption_key' => 'getEncryptionKey',
        'master_pubkey' => 'getMasterPubkey',
        'prune_backups' => 'getPruneBackups',
        'max_protected_backups' => 'getMaxProtectedBackups',
        'fingerprint' => 'getFingerprint',
        'type' => 'getType',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_PBS = 'pbs';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_PBS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('server', $data ?? [], null);
        
        $this->setIfExists('datastore', $data ?? [], null);
        
        $this->setIfExists('namespace', $data ?? [], null);
        
        $this->setIfExists('port', $data ?? [], null);
        
        $this->setIfExists('nodes', $data ?? [], null);
        
        $this->setIfExists('disable', $data ?? [], null);
        
        $this->setIfExists('content', $data ?? [], null);
        
        $this->setIfExists('username', $data ?? [], null);
        
        $this->setIfExists('password', $data ?? [], null);
        
        $this->setIfExists('encryption_key', $data ?? [], null);
        
        $this->setIfExists('master_pubkey', $data ?? [], null);
        
        $this->setIfExists('prune_backups', $data ?? [], null);
        
        $this->setIfExists('max_protected_backups', $data ?? [], null);
        
        $this->setIfExists('fingerprint', $data ?? [], null);
        
        $this->setIfExists('type', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if ($this->container['server'] === null) {
            $invalidProperties[] = "'server' can't be null";
        }
        
        if ($this->container['datastore'] === null) {
            $invalidProperties[] = "'datastore' can't be null";
        }
        
        
        if (!is_null($this->container['port']) && ($this->container['port'] > 65535)) {
            $invalidProperties[] = "invalid value for 'port', must be smaller than or equal to 65535.";
        }

        if (!is_null($this->container['port']) && ($this->container['port'] < 1)) {
            $invalidProperties[] = "invalid value for 'port', must be bigger than or equal to 1.";
        }

        
        
        
        
        
        if (!is_null($this->container['password']) && (mb_strlen($this->container['password']) > 256)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 256.";
        }

        
        
        
        
        if (!is_null($this->container['max_protected_backups']) && ($this->container['max_protected_backups'] < -1)) {
            $invalidProperties[] = "invalid value for 'max_protected_backups', must be bigger than or equal to -1.";
        }

        
        if (!is_null($this->container['fingerprint']) && !preg_match("/([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/", $this->container['fingerprint'])) {
            $invalidProperties[] = "invalid value for 'fingerprint', must be conform to the pattern /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/.";
        }

        
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets server
     *
     * @return string
     */
    public function getServer()
    {
        return $this->container['server'];
    }

    /**
     * Sets server
     *
     * @param string $server Server IP or DNS name.
     *
     * @return self
     */
    public function setServer($server)
    {
        if (is_null($server)) {
            throw new \InvalidArgumentException('non-nullable server cannot be null');
        }
        $this->container['server'] = $server;

        return $this;
    }
    

    /**
     * Gets datastore
     *
     * @return string
     */
    public function getDatastore()
    {
        return $this->container['datastore'];
    }

    /**
     * Sets datastore
     *
     * @param string $datastore Proxmox Backup Server datastore name.
     *
     * @return self
     */
    public function setDatastore($datastore)
    {
        if (is_null($datastore)) {
            throw new \InvalidArgumentException('non-nullable datastore cannot be null');
        }
        $this->container['datastore'] = $datastore;

        return $this;
    }
    

    /**
     * Gets namespace
     *
     * @return string|null
     */
    public function getNamespace()
    {
        return $this->container['namespace'];
    }

    /**
     * Sets namespace
     *
     * @param string|null $namespace Namespace.
     *
     * @return self
     */
    public function setNamespace($namespace)
    {
        if (is_null($namespace)) {
            throw new \InvalidArgumentException('non-nullable namespace cannot be null');
        }
        $this->container['namespace'] = $namespace;

        return $this;
    }
    

    /**
     * Gets port
     *
     * @return int|null
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int|null $port Use this port to connect to the storage instead of the default one (for example, with PBS or ESXi). For NFS and CIFS, use the 'options' option to configure the port via the mount options.
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }

        if (($port > 65535)) {
            throw new \InvalidArgumentException('invalid value for $port when calling PveStoragePbsConfig., must be smaller than or equal to 65535.');
        }
        if (($port < 1)) {
            throw new \InvalidArgumentException('invalid value for $port when calling PveStoragePbsConfig., must be bigger than or equal to 1.');
        }

        $this->container['port'] = $port;

        return $this;
    }
    

    /**
     * Gets nodes
     *
     * @return string|null
     */
    public function getNodes()
    {
        return $this->container['nodes'];
    }

    /**
     * Sets nodes
     *
     * @param string|null $nodes List of nodes for which the storage configuration applies.
     *
     * @return self
     */
    public function setNodes($nodes)
    {
        if (is_null($nodes)) {
            throw new \InvalidArgumentException('non-nullable nodes cannot be null');
        }
        $this->container['nodes'] = $nodes;

        return $this;
    }
    

    /**
     * Gets disable
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getDisable()
    {
        return $this->container['disable'];
    }

    /**
     * Sets disable
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $disable Flag to disable the storage.
     *
     * @return self
     */
    public function setDisable($disable)
    {
        if (is_null($disable)) {
            throw new \InvalidArgumentException('non-nullable disable cannot be null');
        }
        $this->container['disable'] = $disable;

        return $this;
    }
    

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs.
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }
    

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username RBD Id.
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }
    

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password Password for accessing the share/datastore.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        if ((mb_strlen($password) > 256)) {
            throw new \InvalidArgumentException('invalid length for $password when calling PveStoragePbsConfig., must be smaller than or equal to 256.');
        }

        $this->container['password'] = $password;

        return $this;
    }
    

    /**
     * Gets encryption_key
     *
     * @return string|null
     */
    public function getEncryptionKey()
    {
        return $this->container['encryption_key'];
    }

    /**
     * Sets encryption_key
     *
     * @param string|null $encryption_key Encryption key. Use 'autogen' to generate one automatically without passphrase.
     *
     * @return self
     */
    public function setEncryptionKey($encryption_key)
    {
        if (is_null($encryption_key)) {
            throw new \InvalidArgumentException('non-nullable encryption_key cannot be null');
        }
        $this->container['encryption_key'] = $encryption_key;

        return $this;
    }
    

    /**
     * Gets master_pubkey
     *
     * @return string|null
     */
    public function getMasterPubkey()
    {
        return $this->container['master_pubkey'];
    }

    /**
     * Sets master_pubkey
     *
     * @param string|null $master_pubkey Base64-encoded, PEM-formatted public RSA key. Used to encrypt a copy of the encryption-key which will be added to each encrypted backup.
     *
     * @return self
     */
    public function setMasterPubkey($master_pubkey)
    {
        if (is_null($master_pubkey)) {
            throw new \InvalidArgumentException('non-nullable master_pubkey cannot be null');
        }
        $this->container['master_pubkey'] = $master_pubkey;

        return $this;
    }
    

    /**
     * Gets prune_backups
     *
     * @return string|null
     */
    public function getPruneBackups()
    {
        return $this->container['prune_backups'];
    }

    /**
     * Sets prune_backups
     *
     * @param string|null $prune_backups The retention options with shorter intervals are processed first with --keep-last being the very first one. Each option covers a specific period of time. We say that backups within this period are covered by this option. The next option does not take care of already covered backups and only considers older backups.
     *
     * @return self
     */
    public function setPruneBackups($prune_backups)
    {
        if (is_null($prune_backups)) {
            throw new \InvalidArgumentException('non-nullable prune_backups cannot be null');
        }
        $this->container['prune_backups'] = $prune_backups;

        return $this;
    }
    

    /**
     * Gets max_protected_backups
     *
     * @return int|null
     */
    public function getMaxProtectedBackups()
    {
        return $this->container['max_protected_backups'];
    }

    /**
     * Sets max_protected_backups
     *
     * @param int|null $max_protected_backups Maximal number of protected backups per guest. Use '-1' for unlimited.
     *
     * @return self
     */
    public function setMaxProtectedBackups($max_protected_backups)
    {
        if (is_null($max_protected_backups)) {
            throw new \InvalidArgumentException('non-nullable max_protected_backups cannot be null');
        }

        if (($max_protected_backups < -1)) {
            throw new \InvalidArgumentException('invalid value for $max_protected_backups when calling PveStoragePbsConfig., must be bigger than or equal to -1.');
        }

        $this->container['max_protected_backups'] = $max_protected_backups;

        return $this;
    }
    

    /**
     * Gets fingerprint
     *
     * @return string|null
     */
    public function getFingerprint()
    {
        return $this->container['fingerprint'];
    }

    /**
     * Sets fingerprint
     *
     * @param string|null $fingerprint Certificate SHA 256 fingerprint.
     *
     * @return self
     */
    public function setFingerprint($fingerprint)
    {
        if (is_null($fingerprint)) {
            throw new \InvalidArgumentException('non-nullable fingerprint cannot be null');
        }

        if ((!preg_match("/([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/", ObjectSerializer::toString($fingerprint)))) {
            throw new \InvalidArgumentException("invalid value for \$fingerprint when calling PveStoragePbsConfig., must conform to the pattern /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/.");
        }

        $this->container['fingerprint'] = $fingerprint;

        return $this;
    }
    

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



