<?php
/**
 * QemuVmStartRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\PveClient\Model;

use \ArrayAccess;
use \ClientApi\PveClient\ObjectSerializer;

/**
 * QemuVmStartRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\PveClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class QemuVmStartRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'QemuVmStartRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'force_cpu' => 'string',
        'machine' => '\ClientApi\PveClient\Model\PveMachineField',
        'migratedfrom' => 'string',
        'migration_network' => 'string',
        'migration_type' => '\ClientApi\PveClient\Model\PveMigrationTypeEnum',
        'nets_host_mtu' => 'string',
        'skiplock' => '\ClientApi\PveClient\Model\PveBoolean',
        'stateuri' => 'string',
        'targetstorage' => 'string',
        'timeout' => 'int',
        'with_conntrack_state' => '\ClientApi\PveClient\Model\PveBoolean',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'force_cpu' => null,
        'machine' => null,
        'migratedfrom' => 'pve-node',
        'migration_network' => 'CIDR',
        'migration_type' => null,
        'nets_host_mtu' => null,
        'skiplock' => null,
        'stateuri' => null,
        'targetstorage' => 'storage-pair-list',
        'timeout' => 'int64',
        'with_conntrack_state' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'force_cpu' => false,
        'machine' => false,
        'migratedfrom' => false,
        'migration_network' => false,
        'migration_type' => false,
        'nets_host_mtu' => false,
        'skiplock' => false,
        'stateuri' => false,
        'targetstorage' => false,
        'timeout' => false,
        'with_conntrack_state' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'force_cpu' => 'force-cpu',
        'machine' => 'machine',
        'migratedfrom' => 'migratedfrom',
        'migration_network' => 'migration_network',
        'migration_type' => 'migration_type',
        'nets_host_mtu' => 'nets-host-mtu',
        'skiplock' => 'skiplock',
        'stateuri' => 'stateuri',
        'targetstorage' => 'targetstorage',
        'timeout' => 'timeout',
        'with_conntrack_state' => 'with-conntrack-state',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'force_cpu' => 'setForceCpu',
        'machine' => 'setMachine',
        'migratedfrom' => 'setMigratedfrom',
        'migration_network' => 'setMigrationNetwork',
        'migration_type' => 'setMigrationType',
        'nets_host_mtu' => 'setNetsHostMtu',
        'skiplock' => 'setSkiplock',
        'stateuri' => 'setStateuri',
        'targetstorage' => 'setTargetstorage',
        'timeout' => 'setTimeout',
        'with_conntrack_state' => 'setWithConntrackState',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'force_cpu' => 'getForceCpu',
        'machine' => 'getMachine',
        'migratedfrom' => 'getMigratedfrom',
        'migration_network' => 'getMigrationNetwork',
        'migration_type' => 'getMigrationType',
        'nets_host_mtu' => 'getNetsHostMtu',
        'skiplock' => 'getSkiplock',
        'stateuri' => 'getStateuri',
        'targetstorage' => 'getTargetstorage',
        'timeout' => 'getTimeout',
        'with_conntrack_state' => 'getWithConntrackState',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('force_cpu', $data ?? [], null);
        
        $this->setIfExists('machine', $data ?? [], null);
        
        $this->setIfExists('migratedfrom', $data ?? [], null);
        
        $this->setIfExists('migration_network', $data ?? [], null);
        
        $this->setIfExists('migration_type', $data ?? [], null);
        
        $this->setIfExists('nets_host_mtu', $data ?? [], null);
        
        $this->setIfExists('skiplock', $data ?? [], null);
        
        $this->setIfExists('stateuri', $data ?? [], null);
        
        $this->setIfExists('targetstorage', $data ?? [], null);
        
        $this->setIfExists('timeout', $data ?? [], null);
        
        $this->setIfExists('with_conntrack_state', $data ?? [], 0);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        if (!is_null($this->container['migratedfrom']) && !preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $this->container['migratedfrom'])) {
            $invalidProperties[] = "invalid value for 'migratedfrom', must be conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.";
        }

        
        if (!is_null($this->container['migration_network']) && !preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\/[0-9]+|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\/[0-9]{1,2})$/", $this->container['migration_network'])) {
            $invalidProperties[] = "invalid value for 'migration_network', must be conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\/[0-9]+|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\/[0-9]{1,2})$/.";
        }

        
        
        if (!is_null($this->container['nets_host_mtu']) && !preg_match("/net\\d+=\\d+(,net\\d+=\\d+)*/", $this->container['nets_host_mtu'])) {
            $invalidProperties[] = "invalid value for 'nets_host_mtu', must be conform to the pattern /net\\d+=\\d+(,net\\d+=\\d+)*/.";
        }

        
        
        if (!is_null($this->container['stateuri']) && (mb_strlen($this->container['stateuri']) > 128)) {
            $invalidProperties[] = "invalid value for 'stateuri', the character length must be smaller than or equal to 128.";
        }

        
        
        if (!is_null($this->container['timeout']) && ($this->container['timeout'] < 0)) {
            $invalidProperties[] = "invalid value for 'timeout', must be bigger than or equal to 0.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets force_cpu
     *
     * @return string|null
     */
    public function getForceCpu()
    {
        return $this->container['force_cpu'];
    }

    /**
     * Sets force_cpu
     *
     * @param string|null $force_cpu Override QEMU's -cpu argument with the given string.
     *
     * @return self
     */
    public function setForceCpu($force_cpu)
    {
        if (is_null($force_cpu)) {
            throw new \InvalidArgumentException('non-nullable force_cpu cannot be null');
        }
        $this->container['force_cpu'] = $force_cpu;

        return $this;
    }
    

    /**
     * Gets machine
     *
     * @return \ClientApi\PveClient\Model\PveMachineField|null
     */
    public function getMachine()
    {
        return $this->container['machine'];
    }

    /**
     * Sets machine
     *
     * @param \ClientApi\PveClient\Model\PveMachineField|null $machine Specify the QEMU machine.
     *
     * @return self
     */
    public function setMachine($machine)
    {
        if (is_null($machine)) {
            throw new \InvalidArgumentException('non-nullable machine cannot be null');
        }
        $this->container['machine'] = $machine;

        return $this;
    }
    

    /**
     * Gets migratedfrom
     *
     * @return string|null
     */
    public function getMigratedfrom()
    {
        return $this->container['migratedfrom'];
    }

    /**
     * Sets migratedfrom
     *
     * @param string|null $migratedfrom The cluster node name.
     *
     * @return self
     */
    public function setMigratedfrom($migratedfrom)
    {
        if (is_null($migratedfrom)) {
            throw new \InvalidArgumentException('non-nullable migratedfrom cannot be null');
        }

        if ((!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", ObjectSerializer::toString($migratedfrom)))) {
            throw new \InvalidArgumentException("invalid value for \$migratedfrom when calling QemuVmStartRequest., must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }

        $this->container['migratedfrom'] = $migratedfrom;

        return $this;
    }
    

    /**
     * Gets migration_network
     *
     * @return string|null
     */
    public function getMigrationNetwork()
    {
        return $this->container['migration_network'];
    }

    /**
     * Sets migration_network
     *
     * @param string|null $migration_network CIDR of the (sub) network that is used for migration.
     *
     * @return self
     */
    public function setMigrationNetwork($migration_network)
    {
        if (is_null($migration_network)) {
            throw new \InvalidArgumentException('non-nullable migration_network cannot be null');
        }

        if ((!preg_match("/^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\/[0-9]+|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\/[0-9]{1,2})$/", ObjectSerializer::toString($migration_network)))) {
            throw new \InvalidArgumentException("invalid value for \$migration_network when calling QemuVmStartRequest., must conform to the pattern /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\/[0-9]+|(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\/[0-9]{1,2})$/.");
        }

        $this->container['migration_network'] = $migration_network;

        return $this;
    }
    

    /**
     * Gets migration_type
     *
     * @return \ClientApi\PveClient\Model\PveMigrationTypeEnum|null
     */
    public function getMigrationType()
    {
        return $this->container['migration_type'];
    }

    /**
     * Sets migration_type
     *
     * @param \ClientApi\PveClient\Model\PveMigrationTypeEnum|null $migration_type Migration traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.
     *
     * @return self
     */
    public function setMigrationType($migration_type)
    {
        if (is_null($migration_type)) {
            throw new \InvalidArgumentException('non-nullable migration_type cannot be null');
        }
        $this->container['migration_type'] = $migration_type;

        return $this;
    }
    

    /**
     * Gets nets_host_mtu
     *
     * @return string|null
     */
    public function getNetsHostMtu()
    {
        return $this->container['nets_host_mtu'];
    }

    /**
     * Sets nets_host_mtu
     *
     * @param string|null $nets_host_mtu Used for migration compat. List of VirtIO network devices and their effective host_mtu setting according to the QEMU object model on the source side of the migration. A value of 0 means that the host_mtu parameter is to be avoided for the corresponding device.
     *
     * @return self
     */
    public function setNetsHostMtu($nets_host_mtu)
    {
        if (is_null($nets_host_mtu)) {
            throw new \InvalidArgumentException('non-nullable nets_host_mtu cannot be null');
        }

        if ((!preg_match("/net\\d+=\\d+(,net\\d+=\\d+)*/", ObjectSerializer::toString($nets_host_mtu)))) {
            throw new \InvalidArgumentException("invalid value for \$nets_host_mtu when calling QemuVmStartRequest., must conform to the pattern /net\\d+=\\d+(,net\\d+=\\d+)*/.");
        }

        $this->container['nets_host_mtu'] = $nets_host_mtu;

        return $this;
    }
    

    /**
     * Gets skiplock
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getSkiplock()
    {
        return $this->container['skiplock'];
    }

    /**
     * Sets skiplock
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $skiplock Ignore locks - only root is allowed to use this option.
     *
     * @return self
     */
    public function setSkiplock($skiplock)
    {
        if (is_null($skiplock)) {
            throw new \InvalidArgumentException('non-nullable skiplock cannot be null');
        }
        $this->container['skiplock'] = $skiplock;

        return $this;
    }
    

    /**
     * Gets stateuri
     *
     * @return string|null
     */
    public function getStateuri()
    {
        return $this->container['stateuri'];
    }

    /**
     * Sets stateuri
     *
     * @param string|null $stateuri Some command save/restore state from this location.
     *
     * @return self
     */
    public function setStateuri($stateuri)
    {
        if (is_null($stateuri)) {
            throw new \InvalidArgumentException('non-nullable stateuri cannot be null');
        }
        if ((mb_strlen($stateuri) > 128)) {
            throw new \InvalidArgumentException('invalid length for $stateuri when calling QemuVmStartRequest., must be smaller than or equal to 128.');
        }

        $this->container['stateuri'] = $stateuri;

        return $this;
    }
    

    /**
     * Gets targetstorage
     *
     * @return string|null
     */
    public function getTargetstorage()
    {
        return $this->container['targetstorage'];
    }

    /**
     * Sets targetstorage
     *
     * @param string|null $targetstorage Mapping from source to target storages. Providing only a single storage ID maps all source storages to that storage. Providing the special value '1' will map each source storage to itself.
     *
     * @return self
     */
    public function setTargetstorage($targetstorage)
    {
        if (is_null($targetstorage)) {
            throw new \InvalidArgumentException('non-nullable targetstorage cannot be null');
        }
        $this->container['targetstorage'] = $targetstorage;

        return $this;
    }
    

    /**
     * Gets timeout
     *
     * @return int|null
     */
    public function getTimeout()
    {
        return $this->container['timeout'];
    }

    /**
     * Sets timeout
     *
     * @param int|null $timeout Wait maximal timeout seconds.
     *
     * @return self
     */
    public function setTimeout($timeout)
    {
        if (is_null($timeout)) {
            throw new \InvalidArgumentException('non-nullable timeout cannot be null');
        }

        if (($timeout < 0)) {
            throw new \InvalidArgumentException('invalid value for $timeout when calling QemuVmStartRequest., must be bigger than or equal to 0.');
        }

        $this->container['timeout'] = $timeout;

        return $this;
    }
    

    /**
     * Gets with_conntrack_state
     *
     * @return \ClientApi\PveClient\Model\PveBoolean|null
     */
    public function getWithConntrackState()
    {
        return $this->container['with_conntrack_state'];
    }

    /**
     * Sets with_conntrack_state
     *
     * @param \ClientApi\PveClient\Model\PveBoolean|null $with_conntrack_state Whether to migrate conntrack entries for running VMs.
     *
     * @return self
     */
    public function setWithConntrackState($with_conntrack_state)
    {
        if (is_null($with_conntrack_state)) {
            throw new \InvalidArgumentException('non-nullable with_conntrack_state cannot be null');
        }
        $this->container['with_conntrack_state'] = $with_conntrack_state;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



